NumPy

In [6]:
import numpy as np # collection of module
import time
import pandas as pd

In [2]:
intarray1 = np.array([1,2,3,4.5,6],int)

In [3]:
intarray1

array([1, 2, 3, 4, 6])

In [17]:
intarray1[:3]

array([1, 2, 3])

In [76]:
intarray2 = np.array([5,6],int)

In [10]:
intarray2

array([5, 6])

In [18]:
print(np.concatenate((intarray1,intarray2)))

[1 2 3 4 6 5 6]


In [88]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [93]:
# float array
float_array = np.array([[1,2,3],[4,5,6]],float)
float_array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
float_array.shape

(2, 3)

In [95]:
range_array = np.array(range(10),int)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(-1,11,2)

array([-1,  1,  3,  5,  7,  9])

In [27]:
range_array.shape

(10,)

In [97]:
# coverting 1d array to 2d array
range_array = range_array.reshape(5,2)

In [29]:
range_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [105]:
import pandas as pd
s1 = pd.Series({'A':1,'B':2,'C':3,'D':4})
s1


A    1
B    2
C    3
D    4
dtype: int64

In [111]:
s1.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [35]:
shift_code

array([0, 5])

Operations

In [113]:
array1 = np.array([[1,2],[3,4]],int)
print(array1)
array2 = np.array([[11,12],[13,14]],int)
array2

[[1 2]
 [3 4]]


array([[11, 12],
       [13, 14]])

In [114]:
np.sqrt(array1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [118]:
print(np.std(array2))
np.std(array1)

1.118033988749895


1.118033988749895

In [119]:
dummy_array = np.array([range(5),range(5),range(15,20)])
dummy_array

array([[ 0,  1,  2,  3,  4],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [120]:
np.unique(dummy_array)

array([ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19])

In [46]:
array1 = np.arange(start = 12, stop = 240, step = 12)

In [47]:
array1

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [49]:
array1 = np.arange(12,240,12)
array1

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [10]:
np.linspace(start = 1,stop = 20,num = 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [122]:
np.linspace?

Random Array

In [58]:
# generate 5 random values between 0 to 1
np.random.rand(5)

array([0.76828452, 0.88540142, 0.18306028, 0.50304541, 0.97693824])

In [81]:
np.random.seed(100) # to maintain the repeatability or maintain constant values
np.random.rand(5,4) # 5 rows & 4 cols. between o to 1 numbers

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613],
       [0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749, 0.97862378],
       [0.81168315, 0.17194101, 0.81622475, 0.27407375]])

In [15]:
np.random.rand(10)*10

array([7.72640959, 3.86753585, 7.98674704, 0.66368067, 4.36569374,
       4.43162342, 3.07200043, 0.43247066, 4.55969045, 1.30961584])

In [19]:
random1 = np.floor(np.random.rand(10)*10)
random1

array([3., 5., 2., 8., 0., 5., 8., 9., 7., 3.])

In [20]:
np.sort(random1)

array([0., 2., 3., 3., 5., 5., 7., 8., 8., 9.])

In [24]:
xx = np.random.randint(0,20,(2,5)) # 2 is rows & 5 is cols.
xx

array([[ 9, 12, 13,  5, 11],
       [ 8,  3,  8, 16, 13]])

In [25]:
np.unique(xx)

array([ 3,  5,  8,  9, 11, 12, 13, 16])

In [27]:
aa = np.random.randint(0,10,10) # (start,stop,range) 0 to 9 and 10 numbers
aa

array([7, 5, 1, 9, 9, 3, 3, 7, 1, 6])

In [28]:
np.unique(aa)

array([1, 3, 5, 6, 7, 9])

How to extract all numbers between a given range

In [32]:
arr1 = np.arange(-50,50)
arr1

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38,
       -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25,
       -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49])

In [38]:
# method 1 it fetchs the greater than 10 and less than 15 values.
index = np.where((arr1 >= 15) & (arr1 <= 25))
arr1[index]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [34]:
index

(array([60, 61, 62, 63, 64, 65], dtype=int64),)

In [35]:
# method 2
arr1[(arr1 >= 10) & (arr1 <= 15)]

array([10, 11, 12, 13, 14, 15])

How  to print only 3 decimal places in a python numpy array

In [82]:
random_arr = np.random.random([5,3])
random_arr

array([[0.97789926, 0.5730289 , 0.791757  ],
       [0.56155736, 0.87733524, 0.58419583],
       [0.70884983, 0.14853345, 0.42845074],
       [0.69389007, 0.10461974, 0.43960524],
       [0.16620215, 0.50697863, 0.81903586]])

In [83]:
# round off to 3 decimal places
np.set_printoptions(precision=3)
random_arr

array([[0.978, 0.573, 0.792],
       [0.562, 0.877, 0.584],
       [0.709, 0.149, 0.428],
       [0.694, 0.105, 0.44 ],
       [0.166, 0.507, 0.819]])

How to replace all values greater than given value or a cutoff

In [40]:
array_1 = np.arange(12,240,12)
array_1

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [42]:
# method 1 
output_array = np.clip(array_1,a_min=50,a_max=200)
output_array

array([ 50,  50,  50,  50,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 200, 200, 200])

In [86]:
# np.where(condition, if true, if false)

np.where(array_1 < 50,50, array_1)

array([ 50,  50,  50,  50,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [87]:
# method 2
# np.where(condition, true value, false value)
np.where(array_1 < 50, 50, np.where(array_1 > 200,200, array_1))

array([ 50,  50,  50,  50,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 200, 200, 200])

How to drop all missing values from a numpy array

In [44]:
b = np.array([1,2,3,np.nan,5,6,7,np.nan,9])
b

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan,  9.])

In [45]:
np.isnan(b).sum()

2

In [46]:
~np.isnan(b)

array([ True,  True,  True, False,  True,  True,  True, False,  True])

In [47]:
b[np.isnan(b)]

array([nan, nan])

In [48]:
b[~np.isnan(b)]

array([1., 2., 3., 5., 6., 7., 9.])

How to get the position of top n values in numpy array

In [50]:
np.random.seed(100)
a = np.random.randint(0,50,5)
a

array([ 8, 24,  3, 39, 23])

In [51]:
np.sort(a)

array([ 3,  8, 23, 24, 39])

In [54]:
a.argsort()

array([2, 0, 4, 1, 3], dtype=int64)

In [99]:
a.argsort()[-3:]

array([4, 1, 3], dtype=int64)

In [100]:
# acces all the top values
a[a.argsort()[-3:]]

array([23, 24, 39])

Find the common and uncommon elements

In [4]:
# create two list
import numpy as np
a = [1,2,3,4]
b = [1,2,3,4,5,6]
comm_elem = np.intersect1d(a,b)
comm_elem

array([1, 2, 3, 4])

Series

In [56]:
# Data frame
# Series
# values & index
import pandas as pd

In [57]:
arra = np.array(range(5,10))
arra

array([5, 6, 7, 8, 9])

In [63]:
# creating series from a numpy array
x = pd.Series(arra, index=['a','b','c','d','e'])
x 

a    5
b    6
c    7
d    8
e    9
dtype: int32

In [74]:
d = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
df = pd.DataFrame(data=d, index=['A','B','C'])
df

col1  col2
A     1     4
B     2     5
C     3     6

In [75]:
np.shape(df)

(3, 2)

In [76]:
df.index

Index(['A', 'B', 'C'], dtype='object')

In [77]:
df.values

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int64)

In [112]:
x['a']

5

In [113]:
x[0]

5

In [7]:
# axis = 1 stands for cols.
# axis = 0 stands for rows

z1 = pd.Series(np.random.randint(1,6,100)) # no. of bedrooms
z1

0     1
1     3
2     2
3     5
4     5
     ..
95    1
96    4
97    3
98    3
99    2
Length: 100, dtype: int32

In [8]:
z2 = pd.Series(np.random.randint(1,3,100)) # no. of bathrooms
z2

0     1
1     1
2     1
3     2
4     1
     ..
95    1
96    1
97    2
98    1
99    2
Length: 100, dtype: int32

In [9]:
z3 = pd.Series(np.random.randint(10000,90000,100)) # rent per month
z3

0     33281
1     62289
2     24438
3     45615
4     23261
      ...  
95    56211
96    64879
97    19348
98    15729
99    18401
Length: 100, dtype: int32

In [11]:
house_market = pd.concat([z1,z2,z3], axis=1)
house_market

0  1      2
0   1  1  33281
1   3  1  62289
2   2  1  24438
3   5  2  45615
4   5  1  23261
.. .. ..    ...
95  1  1  56211
96  4  1  64879
97  3  2  19348
98  3  1  15729
99  2  2  18401

[100 rows x 3 columns]

In [13]:
house_market = house_market.rename(columns= {0:'Bedrooms',1:'Bathrooms',2:'Rent/month'})
house_market

Bedrooms  Bathrooms  Rent/month
0          1          1       33281
1          3          1       62289
2          2          1       24438
3          5          2       45615
4          5          1       23261
..       ...        ...         ...
95         1          1       56211
96         4          1       64879
97         3          2       19348
98         3          1       15729
99         2          2       18401

[100 rows x 3 columns]

In [14]:
import pandas as pd
import numpy as np
df =pd.read_csv('https://raw.githubusercontent.com/Sreemanto/DSP-55/main/Earthquakes.csv')
df

Date      Time  Latitude  Longitude        Type   Depth  \
0      01/02/1965  13:44:18   19.2460   145.6160  Earthquake  131.60   
1      01/04/1965  11:29:49    1.8630   127.3520  Earthquake   80.00   
2      01/05/1965  18:05:58  -20.5790  -173.9720  Earthquake   20.00   
3      01/08/1965  18:49:43  -59.0760   -23.5570  Earthquake   15.00   
4      01/09/1965  13:32:50   11.9380   126.4270  Earthquake   15.00   
...           ...       ...       ...        ...         ...     ...   
23407  12/28/2016  08:22:12   38.3917  -118.8941  Earthquake   12.30   
23408  12/28/2016  09:13:47   38.3777  -118.8957  Earthquake    8.80   
23409  12/28/2016  12:38:51   36.9179   140.4262  Earthquake   10.00   
23410  12/29/2016  22:30:19   -9.0283   118.6639  Earthquake   79.00   
23411  12/30/2016  20:08:28   37.3973   141.4103  Earthquake   11.94   

       Depth Error  Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0              NaN                     NaN        6.0             MW  ...   
1              NaN                     NaN        5.8             MW  ...   
2              NaN                     NaN        6.2             MW  ...   
3              NaN                     NaN        5.8             MW  ...   
4              NaN                     NaN        5.8             MW  ...   
...            ...                     ...        ...            ...  ...   
23407          1.2                    40.0        5.6             ML  ...   
23408          2.0                    33.0        5.5             ML  ...   
23409          1.8                     NaN        5.9            MWW  ...   
23410          1.8                     NaN        6.3            MWW  ...   
23411          2.2                     NaN        5.5             MB  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                             NaN            NaN                  NaN   
1                             NaN            NaN                  NaN   
2                             NaN            NaN                  NaN   
3                             NaN            NaN                  NaN   
4                             NaN            NaN                  NaN   
...                           ...            ...                  ...   
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square            ID  Source  \
0                   NaN               NaN  ISCGEM860706  ISCGEM   
1                   NaN               NaN  ISCGEM860737  ISCGEM   
2                   NaN               NaN  ISCGEM860762  ISCGEM   
3                   NaN               NaN  ISCGEM860856  ISCGEM   
4                   NaN               NaN  ISCGEM860890  ISCGEM   
...                 ...               ...           ...     ...   
23407               NaN            0.1898    NN00570710      NN   
23408               NaN            0.2187    NN00570744      NN   
23409               4.8            1.5200    US10007NAF      US   
23410               6.0            1.4300    US10007NL0      US   
23411               4.5            0.9100    US10007NTD      US   

      Location Source Magnitude Source     Status  
0              ISCGEM           ISCGEM  Automatic  
1              ISCGEM           ISCGEM  Automatic  
2              ISCGEM           ISCGEM  Automatic  
3              ISCGEM           ISCGEM  Automatic  
4              ISCGEM           ISCGEM  Automatic  
...               ...              ...        ...  
23407              NN               NN   Reviewed  
23408              NN               NN   Reviewed  
23409              US               US   Reviewed  
23410              US

In [15]:
df.shape

(23412, 21)

In [16]:
df.isnull()

Date   Time  Latitude  Longitude   Type  Depth  Depth Error  \
0      False  False     False      False  False  False         True   
1      False  False     False      False  False  False         True   
2      False  False     False      False  False  False         True   
3      False  False     False      False  False  False         True   
4      False  False     False      False  False  False         True   
...      ...    ...       ...        ...    ...    ...          ...   
23407  False  False     False      False  False  False        False   
23408  False  False     False      False  False  False        False   
23409  False  False     False      False  False  False        False   
23410  False  False     False      False  False  False        False   
23411  False  False     False      False  False  False        False   

       Depth Seismic Stations  Magnitude  Magnitude Type  ...  \
0                        True      False           False  ...   
1                        True      False           False  ...   
2                        True      False           False  ...   
3                        True      False           False  ...   
4                        True      False           False  ...   
...                       ...        ...             ...  ...   
23407                   False      False           False  ...   
23408                   False      False           False  ...   
23409                    True      False           False  ...   
23410                    True      False           False  ...   
23411                    True      False           False  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                            True           True                 True   
1                            True           True                 True   
2                            True           True                 True   
3                            True           True                 True   
4                            True           True                 True   
...                           ...            ...                  ...   
23407                       False          False                False   
23408                       False          False                False   
23409                        True          False                False   
23410                        True          False                False   
23411                       False          False                False   

       Horizontal Error  Root Mean Square     ID  Source  Location Source  \
0                  True              True  False   False            False   
1                  True              True  False   False            False   
2                  True              True  False   False            False   
3                  True              True  False   False            False   
4                  True              True  False   False            False   
...                 ...               ...    ...     ...              ...   
23407              True             False  False   False            False   
23408              True             False  False   False            False   
23409             False             False  False   False            False   
23410             False             False  False   False            False   
23411             False             False  False   False            False   

       Magnitude Source  Status  
0                 False   False  
1                 False   False  
2                 False   False  
3                 False   False  
4                 False   False  
...                 ...     ...  
23407             False   False  
23408             False   False  
23409             False   False  
23410             False   False  
23411             False   False  

[23412 rows x 21 columns]

In [17]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [18]:
df.head()

Date      Time  Latitude  Longitude        Type  Depth  Depth Error  \
0  01/02/1965  13:44:18    19.246    145.616  Earthquake  131.6          NaN   
1  01/04/1965  11:29:49     1.863    127.352  Earthquake   80.0          NaN   
2  01/05/1965  18:05:58   -20.579   -173.972  Earthquake   20.0          NaN   
3  01/08/1965  18:49:43   -59.076    -23.557  Earthquake   15.0          NaN   
4  01/09/1965  13:32:50    11.938    126.427  Earthquake   15.0          NaN   

   Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0                     NaN        6.0             MW  ...   
1                     NaN        5.8             MW  ...   
2                     NaN        6.2             MW  ...   
3                     NaN        5.8             MW  ...   
4                     NaN        5.8             MW  ...   

   Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                         NaN            NaN                  NaN   
1                         NaN            NaN                  NaN   
2                         NaN            NaN                  NaN   
3                         NaN            NaN                  NaN   
4                         NaN            NaN                  NaN   

   Horizontal Error  Root Mean Square            ID  Source Location Source  \
0               NaN               NaN  ISCGEM860706  ISCGEM          ISCGEM   
1               NaN               NaN  ISCGEM860737  ISCGEM          ISCGEM   
2               NaN               NaN  ISCGEM860762  ISCGEM          ISCGEM   
3               NaN               NaN  ISCGEM860856  ISCGEM          ISCGEM   
4               NaN               NaN  ISCGEM860890  ISCGEM          ISCGEM   

  Magnitude Source     Status  
0           ISCGEM  Automatic  
1           ISCGEM  Automatic  
2           ISCGEM  Automatic  
3           ISCGEM  Automatic  
4           ISCGEM  Automatic  

[5 rows x 21 columns]

In [19]:
df.tail()

Date      Time  Latitude  Longitude        Type  Depth  \
23407  12/28/2016  08:22:12   38.3917  -118.8941  Earthquake  12.30   
23408  12/28/2016  09:13:47   38.3777  -118.8957  Earthquake   8.80   
23409  12/28/2016  12:38:51   36.9179   140.4262  Earthquake  10.00   
23410  12/29/2016  22:30:19   -9.0283   118.6639  Earthquake  79.00   
23411  12/30/2016  20:08:28   37.3973   141.4103  Earthquake  11.94   

       Depth Error  Depth Seismic Stations  Magnitude Magnitude Type  ...  \
23407          1.2                    40.0        5.6             ML  ...   
23408          2.0                    33.0        5.5             ML  ...   
23409          1.8                     NaN        5.9            MWW  ...   
23410          1.8                     NaN        6.3            MWW  ...   
23411          2.2                     NaN        5.5             MB  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square          ID Source Location Source  \
23407               NaN            0.1898  NN00570710     NN              NN   
23408               NaN            0.2187  NN00570744     NN              NN   
23409               4.8            1.5200  US10007NAF     US              US   
23410               6.0            1.4300  US10007NL0     US              US   
23411               4.5            0.9100  US10007NTD     US              US   

      Magnitude Source    Status  
23407               NN  Reviewed  
23408               NN  Reviewed  
23409               US  Reviewed  
23410               US  Reviewed  
23411               US  Reviewed  

[5 rows x 21 columns]

In [20]:
df.columns

Index(['Date', 'Time', 'Latitude', 'Longitude', 'Type', 'Depth', 'Depth Error',
       'Depth Seismic Stations', 'Magnitude', 'Magnitude Type',
       'Magnitude Error', 'Magnitude Seismic Stations', 'Azimuthal Gap',
       'Horizontal Distance', 'Horizontal Error', 'Root Mean Square', 'ID',
       'Source', 'Location Source', 'Magnitude Source', 'Status'],
      dtype='object')

In [21]:
df[['Date', 'Time', 'Latitude', 'Longitude', 'Type', 'Depth']].head(5)

Date      Time  Latitude  Longitude        Type  Depth
0  01/02/1965  13:44:18    19.246    145.616  Earthquake  131.6
1  01/04/1965  11:29:49     1.863    127.352  Earthquake   80.0
2  01/05/1965  18:05:58   -20.579   -173.972  Earthquake   20.0
3  01/08/1965  18:49:43   -59.076    -23.557  Earthquake   15.0
4  01/09/1965  13:32:50    11.938    126.427  Earthquake   15.0

In [22]:
# dropping a column
df.drop(columns='Date',inplace=True) # inplace = True deleting col. permenantly

In [23]:
df

Time  Latitude  Longitude        Type   Depth  Depth Error  \
0      13:44:18   19.2460   145.6160  Earthquake  131.60          NaN   
1      11:29:49    1.8630   127.3520  Earthquake   80.00          NaN   
2      18:05:58  -20.5790  -173.9720  Earthquake   20.00          NaN   
3      18:49:43  -59.0760   -23.5570  Earthquake   15.00          NaN   
4      13:32:50   11.9380   126.4270  Earthquake   15.00          NaN   
...         ...       ...        ...         ...     ...          ...   
23407  08:22:12   38.3917  -118.8941  Earthquake   12.30          1.2   
23408  09:13:47   38.3777  -118.8957  Earthquake    8.80          2.0   
23409  12:38:51   36.9179   140.4262  Earthquake   10.00          1.8   
23410  22:30:19   -9.0283   118.6639  Earthquake   79.00          1.8   
23411  20:08:28   37.3973   141.4103  Earthquake   11.94          2.2   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
0                         NaN        6.0             MW              NaN   
1                         NaN        5.8             MW              NaN   
2                         NaN        6.2             MW              NaN   
3                         NaN        5.8             MW              NaN   
4                         NaN        5.8             MW              NaN   
...                       ...        ...            ...              ...   
23407                    40.0        5.6             ML            0.320   
23408                    33.0        5.5             ML            0.260   
23409                     NaN        5.9            MWW              NaN   
23410                     NaN        6.3            MWW              NaN   
23411                     NaN        5.5             MB            0.029   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                             NaN            NaN                  NaN   
1                             NaN            NaN                  NaN   
2                             NaN            NaN                  NaN   
3                             NaN            NaN                  NaN   
4                             NaN            NaN                  NaN   
...                           ...            ...                  ...   
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square            ID  Source  \
0                   NaN               NaN  ISCGEM860706  ISCGEM   
1                   NaN               NaN  ISCGEM860737  ISCGEM   
2                   NaN               NaN  ISCGEM860762  ISCGEM   
3                   NaN               NaN  ISCGEM860856  ISCGEM   
4                   NaN               NaN  ISCGEM860890  ISCGEM   
...                 ...               ...           ...     ...   
23407               NaN            0.1898    NN00570710      NN   
23408               NaN            0.2187    NN00570744      NN   
23409               4.8            1.5200    US10007NAF      US   
23410               6.0            1.4300    US10007NL0      US   
23411               4.5            0.9100    US10007NTD      US   

      Location Source Magnitude Source     Status  
0              ISCGEM           ISCGEM  Automatic  
1              ISCGEM           ISCGEM  Automatic  
2              ISCGEM           ISCGEM  Automatic  
3              ISCGEM           ISCGEM  Automatic  
4              ISCGEM           ISCGEM  Automatic  
...               ...              ...        ...  
23407              NN               NN   Reviewed  
23408              NN               NN   Reviewed  
23409              US               US   Reviewed  
23410              

In [11]:
# alternate way
del df['Date']

KeyError: 'Date'

In [24]:
df.describe()

Latitude     Longitude         Depth  Depth Error  \
count  23412.000000  23412.000000  23412.000000  4461.000000   
mean       1.679033     39.639961     70.767911     4.993115   
std       30.113183    125.511959    122.651898     4.875184   
min      -77.080000   -179.997000     -1.100000     0.000000   
25%      -18.653000    -76.349750     14.522500     1.800000   
50%       -3.568500    103.982000     33.000000     3.500000   
75%       26.190750    145.026250     54.000000     6.300000   
max       86.005000    179.998000    700.000000    91.295000   

       Depth Seismic Stations     Magnitude  Magnitude Error  \
count             7097.000000  23412.000000       327.000000   
mean               275.364098      5.882531         0.071820   
std                162.141631      0.423066         0.051466   
min                  0.000000      5.500000         0.000000   
25%                146.000000      5.600000         0.046000   
50%                255.000000      5.700000         0.059000   
75%                384.000000      6.000000         0.075500   
max                934.000000      9.100000         0.410000   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
count                 2564.000000    7299.000000          1604.000000   
mean                    48.944618      44.163532             3.992660   
std                     62.943106      32.141486             5.377262   
min                      0.000000       0.000000             0.004505   
25%                     10.000000      24.100000             0.968750   
50%                     28.000000      36.000000             2.319500   
75%                     66.000000      54.000000             4.724500   
max                    821.000000     360.000000            37.874000   

       Horizontal Error  Root Mean Square  
count       1156.000000      17352.000000  
mean           7.662759          1.022784  
std           10.430396          0.188545  
min            0.085000          0.000000  
25%            5.300000          0.900000  
50%            6.700000          1.000000  
75%            8.100000          1.130000  
max           99.000000          3.440000

In [25]:
df['Latitude'].max()

86.005

In [26]:
df['Latitude'].mean()

1.6790331197719317

In [27]:
df['Latitude'].min()

-77.08

In [28]:
df['Latitude'].median()

-3.5685000000000002

In [29]:
df['Latitude'].mode()

0    -5.902
1    -5.605
2    -5.589
3    51.500
dtype: float64

In [30]:
df.isnull().sum()

Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [31]:
# Impute the null/missing values
df['Magnitude Type']

0         MW
1         MW
2         MW
3         MW
4         MW
        ... 
23407     ML
23408     ML
23409    MWW
23410    MWW
23411     MB
Name: Magnitude Type, Length: 23412, dtype: object

In [32]:
df['Magnitude Type'].unique()

array(['MW', 'ML', 'MH', 'MS', 'MB', 'MWC', 'MD', nan, 'MWB', 'MWW',
       'MWR'], dtype=object)

In [33]:
df['Magnitude Type'].mode()

0    MW
dtype: object

In [34]:
df['Magnitude Type'].mode()[0]

'MW'

In [35]:
# filling those 3 missing values with mode
df['Magnitude Type'].fillna(df['Magnitude Type'].mode()[0],inplace=True)

In [36]:
df.isnull().sum()

Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    0
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [37]:
# unique values
df['Magnitude Type'].unique()

array(['MW', 'ML', 'MH', 'MS', 'MB', 'MWC', 'MD', 'MWB', 'MWW', 'MWR'],
      dtype=object)

In [38]:
# count of unique values
df['Magnitude Type'].nunique()

10

In [28]:
df.nunique?

In [39]:
df['Magnitude Type'].value_counts()

MW     7725
MWC    5669
MB     3761
MWB    2458
MWW    1983
MS     1702
ML       77
MWR      26
MD        6
MH        5
Name: Magnitude Type, dtype: int64

In [40]:
# normalize works as percentage of repeated values
df['Magnitude Type'].value_counts(normalize=True)

MW     0.329959
MWC    0.242141
MB     0.160644
MWB    0.104989
MWW    0.084700
MS     0.072698
ML     0.003289
MWR    0.001111
MD     0.000256
MH     0.000214
Name: Magnitude Type, dtype: float64

In [41]:
df.columns

Index(['Time', 'Latitude', 'Longitude', 'Type', 'Depth', 'Depth Error',
       'Depth Seismic Stations', 'Magnitude', 'Magnitude Type',
       'Magnitude Error', 'Magnitude Seismic Stations', 'Azimuthal Gap',
       'Horizontal Distance', 'Horizontal Error', 'Root Mean Square', 'ID',
       'Source', 'Location Source', 'Magnitude Source', 'Status'],
      dtype='object')

In [42]:
# sorting dataframe
df[['Time', 'Latitude', 'Longitude', 'Type', 'Depth']].sort_values(by='Latitude').head()

Time  Latitude  Longitude        Type  Depth
21304  05:07:02   -77.080   -148.864  Earthquake   12.0
11457  08:34:22   -72.448    174.838  Earthquake   10.0
18716  20:35:37   -67.034    111.199  Earthquake   10.0
4237   03:29:19   -66.448    -82.584  Earthquake   33.0
5717   09:05:44   -65.721   -175.714  Earthquake   10.0

In [43]:
# sorting dataframe
df[['Time', 'Latitude', 'Longitude', 'Type', 'Depth']].sort_values(by='Latitude',ascending=False).head()

Time  Latitude  Longitude        Type  Depth
15812  11:20:52    86.005     31.595  Earthquake   10.0
2910   13:42:43    85.992     30.825  Earthquake   15.0
14294  07:52:46    85.735     84.906  Earthquake   10.0
14255  09:56:35    85.734     84.439  Earthquake   10.0
14288  17:46:46    85.686     86.034  Earthquake   10.0

In [40]:
# filtering syntax : dataframe[dataframe[col name]]
df[df['Magnitude Type']=='MD']

Time   Latitude   Longitude        Type   Depth  Depth Error  \
5523   15:32:11  46.207333 -122.188000  Earthquake   1.510         0.56   
11371  13:34:35  45.035167 -122.606500  Earthquake  19.608         2.84   
11618  03:28:56  42.316167 -122.026667  Earthquake   8.560         0.93   
11620  05:45:35  42.357500 -122.058333  Earthquake   8.530         0.85   
14426  01:43:54  47.074000 -123.463667  Earthquake  40.014         0.06   
15320  18:54:33  47.149000 -122.726667  Earthquake  51.798         0.92   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
5523                     18.0        5.7             MD             0.08   
11371                    40.0        5.6             MD              NaN   
11618                   201.0        5.9             MD             0.02   
11620                   234.0        6.0             MD             0.02   
14426                    48.0        5.8             MD             0.05   
15320                    67.0        6.8             MD             0.03   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
5523                          1.0           62.0             0.008296   
11371                         2.0           67.0             0.206700   
11618                         3.0          129.0                  NaN   
11620                         3.0          128.0                  NaN   
14426                         6.0           85.0                  NaN   
15320                         0.0           31.0                  NaN   

       Horizontal Error  Root Mean Square          ID Source Location Source  \
5523              0.682              0.22  UW10084803     UW              UW   
11371             0.934              0.39  UW10306313     UW              UW   
11618             0.441              0.09  UW10313718     UW              UW   
11620             0.400              0.08  UW10313838     UW              UW   
14426             0.085              0.21  UW10474303     UW              UW   
15320             0.517              0.20  UW10530748     UW              UW   

      Magnitude Source    Status  
5523                UW  Reviewed  
11371               UW  Reviewed  
11618               UW  Reviewed  
11620               UW  Reviewed  
14426               UW  Reviewed  
15320               UW  Reviewed

In [41]:
# operating on the filtered dataframe
df[(df['Type']=='Nuclear Explosion') & (df['Magnitude'] > 6)].head()

Time  Latitude  Longitude               Type  Depth  Depth Error  \
2797  01:22:58    49.986     78.853  Nuclear Explosion    0.0          NaN   
2859  06:59:54    73.302     55.161  Nuclear Explosion    0.0          NaN   
2897  06:59:57    70.779     54.177  Nuclear Explosion    0.0          NaN   
3218  09:59:55    73.366     55.094  Nuclear Explosion    0.0          NaN   
3286  04:59:57    70.817     54.063  Nuclear Explosion    0.0          NaN   

      Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
2797                     NaN        6.3             MB              NaN   
2859                     NaN        6.8             MB              NaN   
2897                     NaN        6.9             MB              NaN   
3218                     NaN        6.4             MB              NaN   
3286                     NaN        6.7             MB              NaN   

      Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
2797                         NaN            NaN                  NaN   
2859                         NaN            NaN                  NaN   
2897                         NaN            NaN                  NaN   
3218                         NaN            NaN                  NaN   
3286                         NaN            NaN                  NaN   

      Horizontal Error  Root Mean Square          ID Source Location Source  \
2797               NaN               NaN  USP00002TP     US              US   
2859               NaN               NaN  USP00003DP     US              US   
2897               NaN               NaN  USP00003YA     US              US   
3218               NaN               NaN  USP00007UG     US              US   
3286               NaN               NaN  USP00008N6     US              US   

     Magnitude Source    Status  
2797               US  Reviewed  
2859               US  Reviewed  
2897               US  Reviewed  
3218               US  Reviewed  
3286               US  Reviewed

In [ ]:
df.describe()

In [42]:
# multiple filters
df[(df['Type']=='Earthquake') & (df['Magnitude'] > 5)].head()

Time  Latitude  Longitude        Type  Depth  Depth Error  \
0  13:44:18    19.246    145.616  Earthquake  131.6          NaN   
1  11:29:49     1.863    127.352  Earthquake   80.0          NaN   
2  18:05:58   -20.579   -173.972  Earthquake   20.0          NaN   
3  18:49:43   -59.076    -23.557  Earthquake   15.0          NaN   
4  13:32:50    11.938    126.427  Earthquake   15.0          NaN   

   Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
0                     NaN        6.0             MW              NaN   
1                     NaN        5.8             MW              NaN   
2                     NaN        6.2             MW              NaN   
3                     NaN        5.8             MW              NaN   
4                     NaN        5.8             MW              NaN   

   Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                         NaN            NaN                  NaN   
1                         NaN            NaN                  NaN   
2                         NaN            NaN                  NaN   
3                         NaN            NaN                  NaN   
4                         NaN            NaN                  NaN   

   Horizontal Error  Root Mean Square            ID  Source Location Source  \
0               NaN               NaN  ISCGEM860706  ISCGEM          ISCGEM   
1               NaN               NaN  ISCGEM860737  ISCGEM          ISCGEM   
2               NaN               NaN  ISCGEM860762  ISCGEM          ISCGEM   
3               NaN               NaN  ISCGEM860856  ISCGEM          ISCGEM   
4               NaN               NaN  ISCGEM860890  ISCGEM          ISCGEM   

  Magnitude Source     Status  
0           ISCGEM  Automatic  
1           ISCGEM  Automatic  
2           ISCGEM  Automatic  
3           ISCGEM  Automatic  
4           ISCGEM  Automatic

In [105]:
ddf = df[(df['Type']=='Nuclear Explosion') & (df['Magnitude'] > 6)].reset_index(drop=True).head()
ddf

Date      Time  Latitude  Longitude               Type  Depth  \
0  07/23/1973  01:22:58    49.986     78.853  Nuclear Explosion    0.0   
1  09/12/1973  06:59:54    73.302     55.161  Nuclear Explosion    0.0   
2  10/27/1973  06:59:57    70.779     54.177  Nuclear Explosion    0.0   
3  08/29/1974  09:59:55    73.366     55.094  Nuclear Explosion    0.0   
4  11/02/1974  04:59:57    70.817     54.063  Nuclear Explosion    0.0   

   Depth Error  Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0          NaN                     NaN        6.3             MB  ...   
1          NaN                     NaN        6.8             MB  ...   
2          NaN                     NaN        6.9             MB  ...   
3          NaN                     NaN        6.4             MB  ...   
4          NaN                     NaN        6.7             MB  ...   

   Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                         NaN            NaN                  NaN   
1                         NaN            NaN                  NaN   
2                         NaN            NaN                  NaN   
3                         NaN            NaN                  NaN   
4                         NaN            NaN                  NaN   

   Horizontal Error  Root Mean Square          ID Source Location Source  \
0               NaN               NaN  USP00002TP     US              US   
1               NaN               NaN  USP00003DP     US              US   
2               NaN               NaN  USP00003YA     US              US   
3               NaN               NaN  USP00007UG     US              US   
4               NaN               NaN  USP00008N6     US              US   

  Magnitude Source    Status  
0               US  Reviewed  
1               US  Reviewed  
2               US  Reviewed  
3               US  Reviewed  
4               US  Reviewed  

[5 rows x 21 columns]

Find the common and uncommon elements

In [59]:
import numpy as np

# create two list

a = [1,2,1,4,2,6,0,1]
b = [1,2,4,6,7,8,9,0]

comm_elem = np.intersect1d(a,b)

uncomm_elem = np.setxor1d(a,b)

In [60]:
np.setdiff1d(a,b)

array([], dtype=int32)

In [61]:
np.setdiff1d(b,a)

array([7, 8, 9])

In [62]:
# a

In [63]:
# b

In [64]:
print("Common Elements are :",comm_elem)
print("Uncommon Elements are :",uncomm_elem)

Common Elements are : [0 1 2 4 6]
Uncommon Elements are : [7 8 9]


Slicing a dataframe

In [107]:
df.iloc[:4,5:9] # 0 to 4 Rows & 5 to 8 cols.

Depth  Depth Error  Depth Seismic Stations  Magnitude
0  131.6          NaN                     NaN        6.0
1   80.0          NaN                     NaN        5.8
2   20.0          NaN                     NaN        6.2
3   15.0          NaN                     NaN        5.8

In [108]:
df.iloc[:,2:8]

Latitude  Longitude        Type   Depth  Depth Error  \
0       19.2460   145.6160  Earthquake  131.60          NaN   
1        1.8630   127.3520  Earthquake   80.00          NaN   
2      -20.5790  -173.9720  Earthquake   20.00          NaN   
3      -59.0760   -23.5570  Earthquake   15.00          NaN   
4       11.9380   126.4270  Earthquake   15.00          NaN   
...         ...        ...         ...     ...          ...   
23407   38.3917  -118.8941  Earthquake   12.30          1.2   
23408   38.3777  -118.8957  Earthquake    8.80          2.0   
23409   36.9179   140.4262  Earthquake   10.00          1.8   
23410   -9.0283   118.6639  Earthquake   79.00          1.8   
23411   37.3973   141.4103  Earthquake   11.94          2.2   

       Depth Seismic Stations  
0                         NaN  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
...                       ...  
23407                    40.0  
23408                    33.0  
23409                     NaN  
23410                     NaN  
23411                     NaN  

[23412 rows x 6 columns]

In [109]:
df.head(3)

Date      Time  Latitude  Longitude        Type  Depth  Depth Error  \
0  01/02/1965  13:44:18    19.246    145.616  Earthquake  131.6          NaN   
1  01/04/1965  11:29:49     1.863    127.352  Earthquake   80.0          NaN   
2  01/05/1965  18:05:58   -20.579   -173.972  Earthquake   20.0          NaN   

   Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0                     NaN        6.0             MW  ...   
1                     NaN        5.8             MW  ...   
2                     NaN        6.2             MW  ...   

   Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                         NaN            NaN                  NaN   
1                         NaN            NaN                  NaN   
2                         NaN            NaN                  NaN   

   Horizontal Error  Root Mean Square            ID  Source Location Source  \
0               NaN               NaN  ISCGEM860706  ISCGEM          ISCGEM   
1               NaN               NaN  ISCGEM860737  ISCGEM          ISCGEM   
2               NaN               NaN  ISCGEM860762  ISCGEM          ISCGEM   

  Magnitude Source     Status  
0           ISCGEM  Automatic  
1           ISCGEM  Automatic  
2           ISCGEM  Automatic  

[3 rows x 21 columns]

Using loc to go to a cell and change a value

In [133]:
df.loc[2797]

Date                                 07/23/1973
Time                                   01:22:58
Latitude                                 49.986
Longitude                                78.853
Type                          Volcanic Eruption
Depth                                         0
Depth Error                                 NaN
Depth Seismic Stations                      NaN
Magnitude                                   6.3
Magnitude Type                               MB
Magnitude Error                             NaN
Magnitude Seismic Stations                  NaN
Azimuthal Gap                               NaN
Horizontal Distance                         NaN
Horizontal Error                            NaN
Root Mean Square                            NaN
ID                                   USP00002TP
Source                                       US
Location Source                              US
Magnitude Source                             US
Status                                 R

In [144]:
df.loc[2797,'Type']

'Volcanic Eruption'

In [146]:
df.loc[2797,'Type'] = 'Tsunami'

In [147]:
df.loc[2797,'Type']

'Tsunami'

Substituting of replacing a value using replace function

In [148]:
df['Type'].replace('Nuclear Explosion','Tsunami',inplace=True)

In [149]:
df.Type.replace('Nuclear Explosion','Tsunami',inplace=True)

In [150]:
df.loc[2797,'Type']

'Tsunami'

Joins

In [90]:
d1 = { 'Name' : ['A','B','C','D'], 
      'ID' : [1,2,3,4]}

df1 = pd.DataFrame(d1)
df1

Name  ID
0    A   1
1    B   2
2    C   3
3    D   4

In [96]:
d2 = { 'Location' : ['North','South','Central','West','East'], 
      'ID' : [1,2,3,4,5]}

df2 = pd.DataFrame(d2)
df2

Location  ID
0    North   1
1    South   2
2  Central   3
3     West   4
4     East   5

In [97]:
pd.merge(df1,df2, how = 'inner', on = 'ID')

Name  ID Location
0    A   1    North
1    B   2    South
2    C   3  Central
3    D   4     West

In [98]:
pd.merge(df1,df2, how = 'left', on ='ID')

Name  ID Location
0    A   1    North
1    B   2    South
2    C   3  Central
3    D   4     West

In [99]:
pd.merge(df1,df2, how = 'right', on = 'ID')

Name  ID Location
0    A   1    North
1    B   2    South
2    C   3  Central
3    D   4     West
4  NaN   5     East

merge Vs Join ??