#### Numpy

In [1]:
import numpy as np
import time

In [2]:
#lets declare a size
size = 100000000

#create two lists
list1 = range(size)
list2 = range(size)

#create two numpy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

In [3]:
#calculate time for python list
start = time.time()
result1 = [(x+y) for x,y in zip(list1,list2)]
print('Time for python lists in msec : ',(time.time() - start))

#calculting for numpy array
start = time.time()
result2 = (arr1 + arr2)
print('Time for numpy array in msec : ',(time.time() - start))

Time for python lists in msec :  20.026864290237427
Time for numpy array in msec :  4.680663585662842


In [4]:
import numpy as np

In [5]:
#defining a numpy array
intarray = np.array([1,2,3,4.5,5],int)

In [6]:
intarray

array([1, 2, 3, 4, 5])

In [7]:
intarray[0]

1

In [8]:
intarray[:3]

array([1, 2, 3])

In [9]:
intarray2 = np.array([5,6],int)

In [10]:
#concatenating two arrays
print(np.concatenate((intarray,intarray2)))

[1 2 3 4 5 5 6]


In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#floatarray
floatarray = np.array([[1,2,3],[4,5,6]])
floatarray

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
floatarray.dtype

dtype('int32')

In [14]:
floatarray.shape

(2, 3)

In [15]:
rangearray = np.array(range(10),int)
rangearray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(-1,11,2)

array([-1,  1,  3,  5,  7,  9])

In [17]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
rangearray.shape

(10,)

In [19]:
#converting 1d array to 2darray
rangearray = rangearray.reshape(5,2)

In [20]:
rangearray

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### Operations

In [21]:
arr1 = np.array([[1,2],[3,4]], int)
print(arr1)
arr2 = np.array([[11,12],[13,14]], int)
arr2

[[1 2]
 [3 4]]


array([[11, 12],
       [13, 14]])

In [22]:
#adding
print('array1 + array2 : \n',(arr1 + arr2))

array1 + array2 : 
 [[12 14]
 [16 18]]


In [23]:
#multiplication
print('Multiplying : \n',(arr1*arr2))

Multiplying : 
 [[11 24]
 [39 56]]


In [24]:
#square
print('Square root : \n',np.sqrt(arr2))

Square root : 
 [[3.31662479 3.46410162]
 [3.60555128 3.74165739]]


In [25]:
#standard deviation
print('Std Dev. : \n',np.std(arr1*arr2))

Std Dev. : 
 16.80029761641144


In [26]:
sample_array = np.array([range(5),range(5),range(15,20)])
sample_array

array([[ 0,  1,  2,  3,  4],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [27]:
np.unique(sample_array)

array([ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19])

In [28]:
array1 = np.arange(start = 12, stop=240, step = 12)
array1

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [29]:
#same
array1 = np.arange(12,240,12)
array1

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [30]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [31]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

#### Random Arrays

In [32]:
print("Random Array : \n",np.random.rand(5))

Random Array : 
 [0.19685373 0.48042147 0.25285876 0.37081763 0.91863315]


In [33]:
#random matrix
np.random.seed(12) #to maintain the repeatability
print("Random Array : \n",np.random.rand(5,4))

Random Array : 
 [[0.15416284 0.7400497  0.26331502 0.53373939]
 [0.01457496 0.91874701 0.90071485 0.03342143]
 [0.95694934 0.13720932 0.28382835 0.60608318]
 [0.94422514 0.85273554 0.00225923 0.52122603]
 [0.55203763 0.48537741 0.76813415 0.16071675]]


In [34]:
# generating random nos between 0-10
np.random.rand(10)*10

array([7.6456045 , 0.20809798, 1.35210178, 1.16273017, 3.09897584,
       6.71452645, 4.71229778, 8.16168298, 2.89586784, 7.33125978])

In [35]:
# random array of integers in a range 0-9
#floor returns the int part of the array
randomarray = np.floor(np.random.rand(10)*10)
randomarray

array([7., 3., 3., 9., 6., 9., 7., 8., 4., 4.])

In [36]:
np.sort(randomarray)

array([3., 3., 4., 4., 6., 7., 7., 8., 9., 9.])

In [37]:
#further simplification
a = np.random.randint(0,10,(2,5))
a

array([[6, 3, 2, 4, 3],
       [9, 6, 7, 4, 1]])

In [38]:
np.sort(a)

array([[2, 3, 3, 4, 6],
       [1, 4, 6, 7, 9]])

In [39]:
#further simplification
np.random.randint(0,10,10)

array([4, 9, 5, 3, 5, 0, 2, 9, 6, 4])

In [40]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [41]:
np.linspace(1,20,4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

#### Q1. How to extract all numbers between a given range

In [42]:
arr1 = np.arange(-50,50)
arr1

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38,
       -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25,
       -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49])

In [43]:
#method1
index = np.where((arr1 >= 15)  & (arr1 <= 35))
arr1[index]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35])

In [44]:
index

(array([65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85], dtype=int64),)

In [45]:
#method2
arr1[(arr1 >= 15) & (arr1 <= 35)]         

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35])

#### Q2. How to print only 3 decimal places in a python numpy array

In [46]:
np.random.random?

In [47]:
np.random.rand?

In [48]:
rand_arr = np.random.random([5,3])
rand_arr

array([[0.5687257 , 0.5006968 , 0.80478954],
       [0.41022121, 0.04858847, 0.57132489],
       [0.26408712, 0.69352745, 0.90983867],
       [0.57339315, 0.63653014, 0.58076778],
       [0.31378165, 0.52633754, 0.64573941]])

In [49]:
np.set_printoptions(precision=2)
rand_arr

array([[0.57, 0.5 , 0.8 ],
       [0.41, 0.05, 0.57],
       [0.26, 0.69, 0.91],
       [0.57, 0.64, 0.58],
       [0.31, 0.53, 0.65]])

In [50]:
#round off to 3 decimal places
np.set_printoptions(precision=3)
rand_arr

array([[0.569, 0.501, 0.805],
       [0.41 , 0.049, 0.571],
       [0.264, 0.694, 0.91 ],
       [0.573, 0.637, 0.581],
       [0.314, 0.526, 0.646]])

#### Q3. Hpw to replace all values greater than a given value or a cutoff

In [51]:
array1 = np.arange(start = 12, stop=240, step = 12)
array1

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [52]:
#method 1
output_array = np.clip(array1 ,a_min=50, a_max=200)
output_array

array([ 50,  50,  50,  50,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 200, 200, 200])

In [53]:
#np.where(condition,if true, if false)

In [54]:
np.where(array1 < 50, 50, array1)

array([ 50,  50,  50,  50,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [55]:
#method 2
np.where(array1 < 50, 50, np.where(array1 > 200, 200, array1))
#np.where(condition, true value, false value)

array([ 50,  50,  50,  50,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 200, 200, 200])

#### Q4. How to drop all missing values from a numpy array

In [56]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan,9])
a

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan,  9.])

In [57]:
np.isnan(a)

array([False, False, False,  True, False, False, False,  True, False])

In [58]:
~np.isnan(a)

array([ True,  True,  True, False,  True,  True,  True, False,  True])

In [59]:
a[np.isnan(a)]

array([nan, nan])

In [60]:
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7., 9.])

##### Q5. How to get the position of top n values in a numpy array

In [61]:
np.random.seed(100)
a = np.random.randint(0,50,5)
a

array([ 8, 24,  3, 39, 23])

In [62]:
np.sort(a)

array([ 3,  8, 23, 24, 39])

In [63]:
a.argsort()

array([2, 0, 4, 1, 3], dtype=int64)

In [64]:
a.argsort()[-3:]

array([4, 1, 3], dtype=int64)

In [65]:
#acces all the top values
a[a.argsort()[-3:]]

array([23, 24, 39])

#### 6. Find the common and uncommon elements

In [66]:
arr1 = np.array(range(7))
arr2 = np.array(range(5,10))

In [67]:
# Print only the common numbers
# Print only the uncommon numbers
print(arr1)
print(arr2)

[0 1 2 3 4 5 6]
[5 6 7 8 9]


In [68]:
#common element
np.intersect1d(arr1,arr2)

array([5, 6])

In [70]:
np.union1d(arr1,arr2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# uncommon values
np.setdiff1d(np.union1d(arr1,arr2),np.intersect1d(arr1,arr2))

array([0, 1, 2, 3, 4, 7, 8, 9])

# Series

In [71]:
import pandas as pd

In [72]:
arr2 = np.array(range(5,10))
arr2

array([5, 6, 7, 8, 9])

In [74]:
#creating series from a numpy array
s1 = pd.Series(arr2,index=['a','b','c','d','e'])
s1

a    5
b    6
c    7
d    8
e    9
dtype: int32

In [75]:
s1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [76]:
s1.values

array([5, 6, 7, 8, 9])

In [77]:
#creating series from a python list
s1 = pd.Series([23,45,67],index=['Chem','Maths','Phy'])
s1

Chem     23
Maths    45
Phy      67
dtype: int64

In [78]:
s1[0]

23

In [79]:
s1["Chem"]

23

In [80]:
type(s1)

pandas.core.series.Series

In [81]:
s1 = pd.Series(np.random.randint(1,6,100)) #no. of bedrroms
s1

0     1
1     3
2     5
3     3
4     3
     ..
95    4
96    4
97    2
98    3
99    4
Length: 100, dtype: int32

In [82]:
s2 = pd.Series(np.random.randint(1,3,100)) #no 0f bathrroms

In [83]:
s3 = pd.Series(np.random.randint(10000,90000,100)) # rent

In [84]:
s3

0     42855
1     73485
2     43274
3     85409
4     88529
      ...  
95    83328
96    31808
97    28310
98    42730
99    63704
Length: 100, dtype: int32

In [85]:
housemkt = pd.concat([s1,s2,s3],axis=1)

In [86]:
housemkt

0  1      2
0   1  1  42855
1   3  2  73485
2   5  2  43274
3   3  2  85409
4   3  2  88529
.. .. ..    ...
95  4  2  83328
96  4  1  31808
97  2  1  28310
98  3  1  42730
99  4  1  63704

[100 rows x 3 columns]

In [87]:
type(housemkt)

pandas.core.frame.DataFrame

In [88]:
#alternate way
housemkt.columns = ["Bedrooms","Bathrooms","Rent/month"]

In [89]:
housemkt

Bedrooms  Bathrooms  Rent/month
0          1          1       42855
1          3          2       73485
2          5          2       43274
3          3          2       85409
4          3          2       88529
..       ...        ...         ...
95         4          2       83328
96         4          1       31808
97         2          1       28310
98         3          1       42730
99         4          1       63704

[100 rows x 3 columns]

In [90]:
housemkt = housemkt.rename(columns = {0:'Bedrooms',
                          1:'Bathrooms',
                          2:'Rent/month'})

In [91]:
housemkt

Bedrooms  Bathrooms  Rent/month
0          1          1       42855
1          3          2       73485
2          5          2       43274
3          3          2       85409
4          3          2       88529
..       ...        ...         ...
95         4          2       83328
96         4          1       31808
97         2          1       28310
98         3          1       42730
99         4          1       63704

[100 rows x 3 columns]

In [92]:
df = pd.read_csv('https://raw.githubusercontent.com/Sreemanto/DSP-55/main/Earthquakes.csv')
df

Date      Time  Latitude  Longitude        Type   Depth  \
0      01/02/1965  13:44:18   19.2460   145.6160  Earthquake  131.60   
1      01/04/1965  11:29:49    1.8630   127.3520  Earthquake   80.00   
2      01/05/1965  18:05:58  -20.5790  -173.9720  Earthquake   20.00   
3      01/08/1965  18:49:43  -59.0760   -23.5570  Earthquake   15.00   
4      01/09/1965  13:32:50   11.9380   126.4270  Earthquake   15.00   
...           ...       ...       ...        ...         ...     ...   
23407  12/28/2016  08:22:12   38.3917  -118.8941  Earthquake   12.30   
23408  12/28/2016  09:13:47   38.3777  -118.8957  Earthquake    8.80   
23409  12/28/2016  12:38:51   36.9179   140.4262  Earthquake   10.00   
23410  12/29/2016  22:30:19   -9.0283   118.6639  Earthquake   79.00   
23411  12/30/2016  20:08:28   37.3973   141.4103  Earthquake   11.94   

       Depth Error  Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0              NaN                     NaN        6.0             MW  ...   
1              NaN                     NaN        5.8             MW  ...   
2              NaN                     NaN        6.2             MW  ...   
3              NaN                     NaN        5.8             MW  ...   
4              NaN                     NaN        5.8             MW  ...   
...            ...                     ...        ...            ...  ...   
23407          1.2                    40.0        5.6             ML  ...   
23408          2.0                    33.0        5.5             ML  ...   
23409          1.8                     NaN        5.9            MWW  ...   
23410          1.8                     NaN        6.3            MWW  ...   
23411          2.2                     NaN        5.5             MB  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                             NaN            NaN                  NaN   
1                             NaN            NaN                  NaN   
2                             NaN            NaN                  NaN   
3                             NaN            NaN                  NaN   
4                             NaN            NaN                  NaN   
...                           ...            ...                  ...   
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square            ID  Source  \
0                   NaN               NaN  ISCGEM860706  ISCGEM   
1                   NaN               NaN  ISCGEM860737  ISCGEM   
2                   NaN               NaN  ISCGEM860762  ISCGEM   
3                   NaN               NaN  ISCGEM860856  ISCGEM   
4                   NaN               NaN  ISCGEM860890  ISCGEM   
...                 ...               ...           ...     ...   
23407               NaN            0.1898    NN00570710      NN   
23408               NaN            0.2187    NN00570744      NN   
23409               4.8            1.5200    US10007NAF      US   
23410               6.0            1.4300    US10007NL0      US   
23411               4.5            0.9100    US10007NTD      US   

      Location Source Magnitude Source     Status  
0              ISCGEM           ISCGEM  Automatic  
1              ISCGEM           ISCGEM  Automatic  
2              ISCGEM           ISCGEM  Automatic  
3              ISCGEM           ISCGEM  Automatic  
4              ISCGEM           ISCGEM  Automatic  
...               ...              ...        ...  
23407              NN               NN   Reviewed  
23408              NN               NN   Reviewed  
23409              US               US   Reviewed  
23410              US

In [93]:
#checcking the dimesnions
df.shape 

(23412, 21)

In [94]:
#checking the nulls
df.isnull()

Date   Time  Latitude  Longitude   Type  Depth  Depth Error  \
0      False  False     False      False  False  False         True   
1      False  False     False      False  False  False         True   
2      False  False     False      False  False  False         True   
3      False  False     False      False  False  False         True   
4      False  False     False      False  False  False         True   
...      ...    ...       ...        ...    ...    ...          ...   
23407  False  False     False      False  False  False        False   
23408  False  False     False      False  False  False        False   
23409  False  False     False      False  False  False        False   
23410  False  False     False      False  False  False        False   
23411  False  False     False      False  False  False        False   

       Depth Seismic Stations  Magnitude  Magnitude Type  ...  \
0                        True      False           False  ...   
1                        True      False           False  ...   
2                        True      False           False  ...   
3                        True      False           False  ...   
4                        True      False           False  ...   
...                       ...        ...             ...  ...   
23407                   False      False           False  ...   
23408                   False      False           False  ...   
23409                    True      False           False  ...   
23410                    True      False           False  ...   
23411                    True      False           False  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                            True           True                 True   
1                            True           True                 True   
2                            True           True                 True   
3                            True           True                 True   
4                            True           True                 True   
...                           ...            ...                  ...   
23407                       False          False                False   
23408                       False          False                False   
23409                        True          False                False   
23410                        True          False                False   
23411                       False          False                False   

       Horizontal Error  Root Mean Square     ID  Source  Location Source  \
0                  True              True  False   False            False   
1                  True              True  False   False            False   
2                  True              True  False   False            False   
3                  True              True  False   False            False   
4                  True              True  False   False            False   
...                 ...               ...    ...     ...              ...   
23407              True             False  False   False            False   
23408              True             False  False   False            False   
23409             False             False  False   False            False   
23410             False             False  False   False            False   
23411             False             False  False   False            False   

       Magnitude Source  Status  
0                 False   False  
1                 False   False  
2                 False   False  
3                 False   False  
4                 False   False  
...                 ...     ...  
23407             False   False  
23408             False   False  
23409             False   False  
23410             False   False  
23411             False   False  

[23412 rows x 21 columns]

In [96]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [97]:
df.head(20)

Date      Time  Latitude  Longitude        Type  Depth  Depth Error  \
0   01/02/1965  13:44:18    19.246    145.616  Earthquake  131.6          NaN   
1   01/04/1965  11:29:49     1.863    127.352  Earthquake   80.0          NaN   
2   01/05/1965  18:05:58   -20.579   -173.972  Earthquake   20.0          NaN   
3   01/08/1965  18:49:43   -59.076    -23.557  Earthquake   15.0          NaN   
4   01/09/1965  13:32:50    11.938    126.427  Earthquake   15.0          NaN   
5   01/10/1965  13:36:32   -13.405    166.629  Earthquake   35.0          NaN   
6   01/12/1965  13:32:25    27.357     87.867  Earthquake   20.0          NaN   
7   01/15/1965  23:17:42   -13.309    166.212  Earthquake   35.0          NaN   
8   01/16/1965  11:32:37   -56.452    -27.043  Earthquake   95.0          NaN   
9   01/17/1965  10:43:17   -24.563    178.487  Earthquake  565.0          NaN   
10  01/17/1965  20:57:41    -6.807    108.988  Earthquake  227.9          NaN   
11  01/24/1965  00:11:17    -2.608    125.952  Earthquake   20.0          NaN   
12  01/29/1965  09:35:30    54.636    161.703  Earthquake   55.0          NaN   
13  02/01/1965  05:27:06   -18.697   -177.864  Earthquake  482.9          NaN   
14  02/02/1965  15:56:51    37.523     73.251  Earthquake   15.0          NaN   
15  02/04/1965  03:25:00   -51.840    139.741  Earthquake   10.0          NaN   
16  02/04/1965  05:01:22    51.251    178.715  Earthquake   30.3          NaN   
17  02/04/1965  06:04:59    51.639    175.055  Earthquake   30.0          NaN   
18  02/04/1965  06:37:06    52.528    172.007  Earthquake   25.0          NaN   
19  02/04/1965  06:39:32    51.626    175.746  Earthquake   25.0          NaN   

    Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0                      NaN        6.0             MW  ...   
1                      NaN        5.8             MW  ...   
2                      NaN        6.2             MW  ...   
3                      NaN        5.8             MW  ...   
4                      NaN        5.8             MW  ...   
5                      NaN        6.7             MW  ...   
6                      NaN        5.9             MW  ...   
7                      NaN        6.0             MW  ...   
8                      NaN        6.0             MW  ...   
9                      NaN        5.8             MW  ...   
10                     NaN        5.9             MW  ...   
11                     NaN        8.2             MW  ...   
12                     NaN        5.5             MW  ...   
13                     NaN        5.6             MW  ...   
14                     NaN        6.0             MW  ...   
15                     NaN        6.1             MW  ...   
16                     NaN        8.7             MW  ...   
17                     NaN        6.0             MW  ...   
18                     NaN        5.7             MW  ...   
19                     NaN        5.8             MW  ...   

    Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                          NaN            NaN                  NaN   
1                          NaN            NaN                  NaN   
2                          NaN            NaN                  NaN   
3                          NaN            NaN                  NaN   
4                          NaN            NaN                  NaN   
5                          NaN            NaN                  NaN   
6                          NaN            NaN                  NaN   
7                          NaN            NaN                  NaN   
8                          NaN            NaN                  NaN   
9                          NaN            NaN                  NaN   
10                         NaN            NaN                  NaN   
11                         NaN            NaN                  NaN   
12                         NaN            NaN                  NaN   
13                         NaN            NaN 

In [98]:
df.tail(5)

Date      Time  Latitude  Longitude        Type  Depth  \
23407  12/28/2016  08:22:12   38.3917  -118.8941  Earthquake  12.30   
23408  12/28/2016  09:13:47   38.3777  -118.8957  Earthquake   8.80   
23409  12/28/2016  12:38:51   36.9179   140.4262  Earthquake  10.00   
23410  12/29/2016  22:30:19   -9.0283   118.6639  Earthquake  79.00   
23411  12/30/2016  20:08:28   37.3973   141.4103  Earthquake  11.94   

       Depth Error  Depth Seismic Stations  Magnitude Magnitude Type  ...  \
23407          1.2                    40.0        5.6             ML  ...   
23408          2.0                    33.0        5.5             ML  ...   
23409          1.8                     NaN        5.9            MWW  ...   
23410          1.8                     NaN        6.3            MWW  ...   
23411          2.2                     NaN        5.5             MB  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square          ID Source Location Source  \
23407               NaN            0.1898  NN00570710     NN              NN   
23408               NaN            0.2187  NN00570744     NN              NN   
23409               4.8            1.5200  US10007NAF     US              US   
23410               6.0            1.4300  US10007NL0     US              US   
23411               4.5            0.9100  US10007NTD     US              US   

      Magnitude Source    Status  
23407               NN  Reviewed  
23408               NN  Reviewed  
23409               US  Reviewed  
23410               US  Reviewed  
23411               US  Reviewed  

[5 rows x 21 columns]

In [99]:
#selecting limited columns
df.columns

Index(['Date', 'Time', 'Latitude', 'Longitude', 'Type', 'Depth', 'Depth Error',
       'Depth Seismic Stations', 'Magnitude', 'Magnitude Type',
       'Magnitude Error', 'Magnitude Seismic Stations', 'Azimuthal Gap',
       'Horizontal Distance', 'Horizontal Error', 'Root Mean Square', 'ID',
       'Source', 'Location Source', 'Magnitude Source', 'Status'],
      dtype='object')

In [100]:
#single column
df['Horizontal Distance']
#df.Horizontal Distance

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
         ...  
23407    0.120
23408    0.129
23409    0.992
23410    3.553
23411    0.681
Name: Horizontal Distance, Length: 23412, dtype: float64

In [102]:
df["Date"].head(5)

0    01/02/1965
1    01/04/1965
2    01/05/1965
3    01/08/1965
4    01/09/1965
Name: Date, dtype: object

In [101]:
df.Date

0        01/02/1965
1        01/04/1965
2        01/05/1965
3        01/08/1965
4        01/09/1965
            ...    
23407    12/28/2016
23408    12/28/2016
23409    12/28/2016
23410    12/29/2016
23411    12/30/2016
Name: Date, Length: 23412, dtype: object

In [103]:
# selecting multiple columns
df[['Date', 'Time', 'Latitude', 'Longitude']]

Date      Time  Latitude  Longitude
0      01/02/1965  13:44:18   19.2460   145.6160
1      01/04/1965  11:29:49    1.8630   127.3520
2      01/05/1965  18:05:58  -20.5790  -173.9720
3      01/08/1965  18:49:43  -59.0760   -23.5570
4      01/09/1965  13:32:50   11.9380   126.4270
...           ...       ...       ...        ...
23407  12/28/2016  08:22:12   38.3917  -118.8941
23408  12/28/2016  09:13:47   38.3777  -118.8957
23409  12/28/2016  12:38:51   36.9179   140.4262
23410  12/29/2016  22:30:19   -9.0283   118.6639
23411  12/30/2016  20:08:28   37.3973   141.4103

[23412 rows x 4 columns]

In [104]:
#droppiong a column
df.drop(columns = 'Date')

Time  Latitude  Longitude        Type   Depth  Depth Error  \
0      13:44:18   19.2460   145.6160  Earthquake  131.60          NaN   
1      11:29:49    1.8630   127.3520  Earthquake   80.00          NaN   
2      18:05:58  -20.5790  -173.9720  Earthquake   20.00          NaN   
3      18:49:43  -59.0760   -23.5570  Earthquake   15.00          NaN   
4      13:32:50   11.9380   126.4270  Earthquake   15.00          NaN   
...         ...       ...        ...         ...     ...          ...   
23407  08:22:12   38.3917  -118.8941  Earthquake   12.30          1.2   
23408  09:13:47   38.3777  -118.8957  Earthquake    8.80          2.0   
23409  12:38:51   36.9179   140.4262  Earthquake   10.00          1.8   
23410  22:30:19   -9.0283   118.6639  Earthquake   79.00          1.8   
23411  20:08:28   37.3973   141.4103  Earthquake   11.94          2.2   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
0                         NaN        6.0             MW              NaN   
1                         NaN        5.8             MW              NaN   
2                         NaN        6.2             MW              NaN   
3                         NaN        5.8             MW              NaN   
4                         NaN        5.8             MW              NaN   
...                       ...        ...            ...              ...   
23407                    40.0        5.6             ML            0.320   
23408                    33.0        5.5             ML            0.260   
23409                     NaN        5.9            MWW              NaN   
23410                     NaN        6.3            MWW              NaN   
23411                     NaN        5.5             MB            0.029   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                             NaN            NaN                  NaN   
1                             NaN            NaN                  NaN   
2                             NaN            NaN                  NaN   
3                             NaN            NaN                  NaN   
4                             NaN            NaN                  NaN   
...                           ...            ...                  ...   
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square            ID  Source  \
0                   NaN               NaN  ISCGEM860706  ISCGEM   
1                   NaN               NaN  ISCGEM860737  ISCGEM   
2                   NaN               NaN  ISCGEM860762  ISCGEM   
3                   NaN               NaN  ISCGEM860856  ISCGEM   
4                   NaN               NaN  ISCGEM860890  ISCGEM   
...                 ...               ...           ...     ...   
23407               NaN            0.1898    NN00570710      NN   
23408               NaN            0.2187    NN00570744      NN   
23409               4.8            1.5200    US10007NAF      US   
23410               6.0            1.4300    US10007NL0      US   
23411               4.5            0.9100    US10007NTD      US   

      Location Source Magnitude Source     Status  
0              ISCGEM           ISCGEM  Automatic  
1              ISCGEM           ISCGEM  Automatic  
2              ISCGEM           ISCGEM  Automatic  
3              ISCGEM           ISCGEM  Automatic  
4              ISCGEM           ISCGEM  Automatic  
...               ...              ...        ...  
23407              NN               NN   Reviewed  
23408              NN               NN   Reviewed  
23409              US               US   Reviewed  
23410              

In [105]:
#df = df.drop(columns = 'Date')

In [106]:
#droppiong a column
df.drop(columns = 'Date',inplace = True)

In [107]:
#Alterante way
del df["Date"]

KeyError: 'Date'

In [ ]:
df

In [108]:
df.describe()

Latitude     Longitude         Depth  Depth Error  \
count  23412.000000  23412.000000  23412.000000  4461.000000   
mean       1.679033     39.639961     70.767911     4.993115   
std       30.113183    125.511959    122.651898     4.875184   
min      -77.080000   -179.997000     -1.100000     0.000000   
25%      -18.653000    -76.349750     14.522500     1.800000   
50%       -3.568500    103.982000     33.000000     3.500000   
75%       26.190750    145.026250     54.000000     6.300000   
max       86.005000    179.998000    700.000000    91.295000   

       Depth Seismic Stations     Magnitude  Magnitude Error  \
count             7097.000000  23412.000000       327.000000   
mean               275.364098      5.882531         0.071820   
std                162.141631      0.423066         0.051466   
min                  0.000000      5.500000         0.000000   
25%                146.000000      5.600000         0.046000   
50%                255.000000      5.700000         0.059000   
75%                384.000000      6.000000         0.075500   
max                934.000000      9.100000         0.410000   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
count                 2564.000000    7299.000000          1604.000000   
mean                    48.944618      44.163532             3.992660   
std                     62.943106      32.141486             5.377262   
min                      0.000000       0.000000             0.004505   
25%                     10.000000      24.100000             0.968750   
50%                     28.000000      36.000000             2.319500   
75%                     66.000000      54.000000             4.724500   
max                    821.000000     360.000000            37.874000   

       Horizontal Error  Root Mean Square  
count       1156.000000      17352.000000  
mean           7.662759          1.022784  
std           10.430396          0.188545  
min            0.085000          0.000000  
25%            5.300000          0.900000  
50%            6.700000          1.000000  
75%            8.100000          1.130000  
max           99.000000          3.440000

In [109]:
df['Latitude'].max()

86.005

In [110]:
df['Latitude'].min()

-77.08

In [111]:
df['Latitude'].mean()

1.6790331197719317

In [112]:
df.isnull().sum()

Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [113]:
#impute the null values
df["Magnitude Type"]

0         MW
1         MW
2         MW
3         MW
4         MW
        ... 
23407     ML
23408     ML
23409    MWW
23410    MWW
23411     MB
Name: Magnitude Type, Length: 23412, dtype: object

In [114]:
df["Magnitude Type"].unique()

array(['MW', 'ML', 'MH', 'MS', 'MB', 'MWC', 'MD', nan, 'MWB', 'MWW',
       'MWR'], dtype=object)

In [115]:
df["Magnitude Type"].mode()

0    MW
dtype: object

In [116]:
df["Magnitude Type"].mode()[0]

'MW'

In [117]:
#filling those 3 missing values with mode
df["Magnitude Type"].fillna(df["Magnitude Type"].mode()[0],inplace=True)

In [118]:
df.isnull().sum()

Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    0
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [119]:
#unique values
df["Magnitude Type"].unique()

array(['MW', 'ML', 'MH', 'MS', 'MB', 'MWC', 'MD', 'MWB', 'MWW', 'MWR'],
      dtype=object)

In [120]:
#count of unique values
df["Magnitude Type"].nunique()

10

In [122]:
df["Magnitude Type"].value_counts()

MW     7725
MWC    5669
MB     3761
MWB    2458
MWW    1983
MS     1702
ML       77
MWR      26
MD        6
MH        5
Name: Magnitude Type, dtype: int64

In [123]:
df["Magnitude Type"].value_counts(normalize=True)

MW     0.329959
MWC    0.242141
MB     0.160644
MWB    0.104989
MWW    0.084700
MS     0.072698
ML     0.003289
MWR    0.001111
MD     0.000256
MH     0.000214
Name: Magnitude Type, dtype: float64

In [124]:
df[[ 'Latitude', 'Longitude', 'Type', 'Depth']].head(5)

Latitude  Longitude        Type  Depth
0    19.246    145.616  Earthquake  131.6
1     1.863    127.352  Earthquake   80.0
2   -20.579   -173.972  Earthquake   20.0
3   -59.076    -23.557  Earthquake   15.0
4    11.938    126.427  Earthquake   15.0

In [125]:
#sorting a dataframe
df[[ 'Latitude', 'Longitude', 'Type', 'Depth']].sort_values(by='Latitude')

Latitude  Longitude        Type  Depth
21304   -77.080   -148.864  Earthquake   12.0
11457   -72.448    174.838  Earthquake   10.0
18716   -67.034    111.199  Earthquake   10.0
4237    -66.448    -82.584  Earthquake   33.0
5717    -65.721   -175.714  Earthquake   10.0
...         ...        ...         ...    ...
14288    85.686     86.034  Earthquake   10.0
14255    85.734     84.439  Earthquake   10.0
14294    85.735     84.906  Earthquake   10.0
2910     85.992     30.825  Earthquake   15.0
15812    86.005     31.595  Earthquake   10.0

[23412 rows x 4 columns]

In [126]:
df[[ 'Latitude', 'Longitude', 'Type', 'Depth']].sort_values(by='Latitude',ascending=False)

Latitude  Longitude        Type  Depth
15812    86.005     31.595  Earthquake   10.0
2910     85.992     30.825  Earthquake   15.0
14294    85.735     84.906  Earthquake   10.0
14255    85.734     84.439  Earthquake   10.0
14288    85.686     86.034  Earthquake   10.0
...         ...        ...         ...    ...
5717    -65.721   -175.714  Earthquake   10.0
4237    -66.448    -82.584  Earthquake   33.0
18716   -67.034    111.199  Earthquake   10.0
11457   -72.448    174.838  Earthquake   10.0
21304   -77.080   -148.864  Earthquake   12.0

[23412 rows x 4 columns]

In [ ]:
#dataframe[dataframe[col name]]

In [127]:
#filtering dataframes
df[df['Magnitude Type']=="MD"]

Time   Latitude   Longitude        Type   Depth  Depth Error  \
5523   15:32:11  46.207333 -122.188000  Earthquake   1.510         0.56   
11371  13:34:35  45.035167 -122.606500  Earthquake  19.608         2.84   
11618  03:28:56  42.316167 -122.026667  Earthquake   8.560         0.93   
11620  05:45:35  42.357500 -122.058333  Earthquake   8.530         0.85   
14426  01:43:54  47.074000 -123.463667  Earthquake  40.014         0.06   
15320  18:54:33  47.149000 -122.726667  Earthquake  51.798         0.92   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
5523                     18.0        5.7             MD             0.08   
11371                    40.0        5.6             MD              NaN   
11618                   201.0        5.9             MD             0.02   
11620                   234.0        6.0             MD             0.02   
14426                    48.0        5.8             MD             0.05   
15320                    67.0        6.8             MD             0.03   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
5523                          1.0           62.0             0.008296   
11371                         2.0           67.0             0.206700   
11618                         3.0          129.0                  NaN   
11620                         3.0          128.0                  NaN   
14426                         6.0           85.0                  NaN   
15320                         0.0           31.0                  NaN   

       Horizontal Error  Root Mean Square          ID Source Location Source  \
5523              0.682              0.22  UW10084803     UW              UW   
11371             0.934              0.39  UW10306313     UW              UW   
11618             0.441              0.09  UW10313718     UW              UW   
11620             0.400              0.08  UW10313838     UW              UW   
14426             0.085              0.21  UW10474303     UW              UW   
15320             0.517              0.20  UW10530748     UW              UW   

      Magnitude Source    Status  
5523                UW  Reviewed  
11371               UW  Reviewed  
11618               UW  Reviewed  
11620               UW  Reviewed  
14426               UW  Reviewed  
15320               UW  Reviewed

In [128]:
#operating on the filtered dataframe
df[df['Magnitude Type']=="MD"][['Time','Latitude']]

Time   Latitude
5523   15:32:11  46.207333
11371  13:34:35  45.035167
11618  03:28:56  42.316167
11620  05:45:35  42.357500
14426  01:43:54  47.074000
15320  18:54:33  47.149000

In [ ]:
df[df['Magnitude Type']=="MD"]["Depth"].max()

In [133]:
ddf = df[(df['Type']=='Nuclear Explosion') & (df['Magnitude']>6)].reset_index(drop=True)

In [134]:
ddf

Time  Latitude  Longitude               Type  Depth  Depth Error  \
0   01:22:58    49.986     78.853  Nuclear Explosion    0.0          NaN   
1   06:59:54    73.302     55.161  Nuclear Explosion    0.0          NaN   
2   06:59:57    70.779     54.177  Nuclear Explosion    0.0          NaN   
3   09:59:55    73.366     55.094  Nuclear Explosion    0.0          NaN   
4   04:59:57    70.817     54.063  Nuclear Explosion    0.0          NaN   
5   08:59:56    70.843     53.690  Nuclear Explosion    0.0          NaN   
6   11:59:57    73.351     55.078  Nuclear Explosion    0.0          NaN   
7   02:56:58    49.918     78.915  Nuclear Explosion    0.0          NaN   
8   03:56:57    49.901     78.959  Nuclear Explosion    0.0          NaN   
9   02:51:57    49.971     79.010  Nuclear Explosion    0.0          NaN   
10  04:56:58    49.964     78.827  Nuclear Explosion    0.0          NaN   
11  02:42:39    49.976     78.889  Nuclear Explosion    0.0          NaN   
12  03:43:14    49.909     78.873  Nuclear Explosion    0.0          NaN   
13  03:23:05    49.889     78.931  Nuclear Explosion    0.0          NaN   
14  01:17:14    49.995     78.856  Nuclear Explosion    0.0          NaN   
15  03:37:13    49.928     78.869  Nuclear Explosion    0.0          NaN   
16  02:36:44    49.906     78.981  Nuclear Explosion    0.0          NaN   
17  01:55:05    49.921     78.907  Nuclear Explosion    0.0          NaN   
18  01:09:11    49.891     78.963  Nuclear Explosion    0.0          NaN   
19  01:50:11    49.949     78.834  Nuclear Explosion    0.0          NaN   
20  03:55:03    49.957     78.862  Nuclear Explosion    0.0          NaN   
21  01:17:08    49.928     78.829  Nuclear Explosion    0.0          NaN   
22  04:59:58    41.584     88.737  Nuclear Explosion    0.0          NaN   
23  00:53:05    49.913     78.735  Nuclear Explosion    0.0          NaN   
24  03:21:05    49.989     78.844  Nuclear Explosion    0.0          NaN   
25  03:05:05    49.864     78.758  Nuclear Explosion    0.0          NaN   
26  03:05:06    49.954     78.910  Nuclear Explosion    0.0          NaN   
27  01:33:06    49.917     78.945  Nuclear Explosion    0.0          NaN   
28  00:57:07    49.928     78.769  Nuclear Explosion    0.0          NaN   
29  03:59:57    49.833     78.808  Nuclear Explosion    0.0          NaN   
30  03:57:07    49.924     78.831  Nuclear Explosion    0.0          NaN   
31  04:59:58    41.564     88.770  Nuclear Explosion    0.0          NaN   
32  04:59:58    41.604     88.813  Nuclear Explosion    0.0          NaN   
33  04:05:58    41.603     88.820  Nuclear Explosion    0.0          NaN   

    Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
0                      NaN        6.3             MB              NaN   
1                      NaN        6.8             MB              NaN   
2                      NaN        6.9             MB              NaN   
3                      NaN        6.4             MB              NaN   
4                      NaN        6.7             MB              NaN   
5                      NaN        6.7             MB              NaN   
6                      NaN        6.5             MB              NaN   
7                      NaN        6.3             MB              NaN   
8                      NaN        6.1             MB              NaN   
9                      NaN        6.1             MB              NaN   
10                     NaN        6.1             MB              NaN   
11                     NaN        6.2             MB              NaN   
12                     NaN        6.2             MB              NaN   
13                     NaN        6.1             MB              NaN   
14                     NaN        6.1             MB              NaN   
15                     NaN        6.1             MB              NaN   
16                     NaN        6.1             MB              NaN   
17                     NaN       

In [135]:
#Creating a new column
df['New Magnitude'] = df['Magnitude'] + 0.5

In [136]:
df[['Magnitude','New Magnitude']]

Magnitude  New Magnitude
0            6.0            6.5
1            5.8            6.3
2            6.2            6.7
3            5.8            6.3
4            5.8            6.3
...          ...            ...
23407        5.6            6.1
23408        5.5            6.0
23409        5.9            6.4
23410        6.3            6.8
23411        5.5            6.0

[23412 rows x 2 columns]

In [139]:
#classify earthquakes greater than 7 disaster, not a disaster

df['Is_Disaster'] = np.where(df['Magnitude'] > 7, 'Yes', "No")

In [141]:
df[df['Magnitude'] > 7 ]

Time  Latitude  Longitude        Type   Depth  Depth Error  \
11     00:11:17   -2.6080   125.9520  Earthquake   20.00          NaN   
16     05:01:22   51.2510   178.7150  Earthquake   30.30          NaN   
26     08:40:44   51.4430   179.6050  Earthquake   30.00          NaN   
87     15:53:07   36.4050    70.7240  Earthquake  207.80          NaN   
100    16:33:16  -32.5220   -71.2330  Earthquake   70.00          NaN   
...         ...       ...        ...         ...     ...          ...   
23230  04:29:58   -0.0456   -17.8255  Earthquake   10.00          1.7   
23326  11:02:56  -42.7358   173.0499  Earthquake   15.22          3.2   
23369  17:38:46  -10.6787   161.3214  Earthquake   40.00          1.8   
23386  10:51:10   -4.5049   153.5216  Earthquake   94.54          3.8   
23403  14:22:27  -43.4029   -73.9395  Earthquake   38.00          1.9   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  ...  \
11                        NaN        8.2             MW              NaN  ...   
16                        NaN        8.7             MW              NaN  ...   
26                        NaN        7.3             MW              NaN  ...   
87                        NaN        7.4             MW              NaN  ...   
100                       NaN        7.4             MW              NaN  ...   
...                       ...        ...            ...              ...  ...   
23230                     NaN        7.1            MWW              NaN  ...   
23326                     NaN        7.8            MWW              NaN  ...   
23369                     NaN        7.8            MWW              NaN  ...   
23386                     NaN        7.9            MWW              NaN  ...   
23403                     NaN        7.6            MWW              NaN  ...   

       Horizontal Error  Root Mean Square                         ID  \
11                  NaN               NaN               ISCGEM861299   
16                  NaN               NaN  OFFICIAL19650204050122_30   
26                  NaN               NaN               ISCGEM859264   
87                  NaN               NaN               ISCGEM858598   
100                 NaN               NaN               ISCGEM858940   
...                 ...               ...                        ...   
23230               8.4              0.87                 US20006UY6   
23326               4.6              0.57                 US1000778I   
23369               8.2              0.87                 US20007Z80   
23386               7.3              0.97                 US200081V8   
23403               6.8              0.80                 US10007MN3   

         Source  Location Source Magnitude Source     Status New Magnitude  \
11       ISCGEM           ISCGEM           ISCGEM  Automatic           8.7   
16     OFFICIAL           ISCGEM         OFFICIAL  Automatic           9.2   
26       ISCGEM           ISCGEM           ISCGEM  Automatic           7.8   
87       ISCGEM           ISCGEM           ISCGEM  Automatic           7.9   
100      ISCGEM           ISCGEM           ISCGEM  Automatic           7.9   
...         ...              ...              ...        ...           ...   
23230        US               US               US   Reviewed           7.6   
23326        US               US               US   Reviewed           8.3   
23369        US               US               US   Reviewed           8.3   
23386        US               US               US   Reviewed           8.4   
23403        US               US               US   Reviewed           8.1   

      new col Is_Disaster  
11      value         Yes  
16      value         Yes  
26      value         Yes  
87      value         Yes  
100     value         Yes  
...       ...         ...  
23230   value         Yes  
23326   value         Yes  
23369   value         Yes  
23386   value         Yes  
23403   value         Yes  

[570 rows x 23 columns

In [137]:
df['new col'] = 'value'

In [138]:
df

Time  Latitude  Longitude        Type   Depth  Depth Error  \
0      13:44:18   19.2460   145.6160  Earthquake  131.60          NaN   
1      11:29:49    1.8630   127.3520  Earthquake   80.00          NaN   
2      18:05:58  -20.5790  -173.9720  Earthquake   20.00          NaN   
3      18:49:43  -59.0760   -23.5570  Earthquake   15.00          NaN   
4      13:32:50   11.9380   126.4270  Earthquake   15.00          NaN   
...         ...       ...        ...         ...     ...          ...   
23407  08:22:12   38.3917  -118.8941  Earthquake   12.30          1.2   
23408  09:13:47   38.3777  -118.8957  Earthquake    8.80          2.0   
23409  12:38:51   36.9179   140.4262  Earthquake   10.00          1.8   
23410  22:30:19   -9.0283   118.6639  Earthquake   79.00          1.8   
23411  20:08:28   37.3973   141.4103  Earthquake   11.94          2.2   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  ...  \
0                         NaN        6.0             MW              NaN  ...   
1                         NaN        5.8             MW              NaN  ...   
2                         NaN        6.2             MW              NaN  ...   
3                         NaN        5.8             MW              NaN  ...   
4                         NaN        5.8             MW              NaN  ...   
...                       ...        ...            ...              ...  ...   
23407                    40.0        5.6             ML            0.320  ...   
23408                    33.0        5.5             ML            0.260  ...   
23409                     NaN        5.9            MWW              NaN  ...   
23410                     NaN        6.3            MWW              NaN  ...   
23411                     NaN        5.5             MB            0.029  ...   

       Horizontal Distance  Horizontal Error  Root Mean Square            ID  \
0                      NaN               NaN               NaN  ISCGEM860706   
1                      NaN               NaN               NaN  ISCGEM860737   
2                      NaN               NaN               NaN  ISCGEM860762   
3                      NaN               NaN               NaN  ISCGEM860856   
4                      NaN               NaN               NaN  ISCGEM860890   
...                    ...               ...               ...           ...   
23407                0.120               NaN            0.1898    NN00570710   
23408                0.129               NaN            0.2187    NN00570744   
23409                0.992               4.8            1.5200    US10007NAF   
23410                3.553               6.0            1.4300    US10007NL0   
23411                0.681               4.5            0.9100    US10007NTD   

       Source Location Source Magnitude Source     Status New Magnitude  \
0      ISCGEM          ISCGEM           ISCGEM  Automatic           6.5   
1      ISCGEM          ISCGEM           ISCGEM  Automatic           6.3   
2      ISCGEM          ISCGEM           ISCGEM  Automatic           6.7   
3      ISCGEM          ISCGEM           ISCGEM  Automatic           6.3   
4      ISCGEM          ISCGEM           ISCGEM  Automatic           6.3   
...       ...             ...              ...        ...           ...   
23407      NN              NN               NN   Reviewed           6.1   
23408      NN              NN               NN   Reviewed           6.0   
23409      US              US               US   Reviewed           6.4   
23410      US              US               US   Reviewed           6.8   
23411      US              US               US   Reviewed           6.0   

      new col  
0       value  
1       value  
2       value  
3       value  
4       value  
...       ...  
23407   value  
23408   value  
23409   value  
23410   value  
23411   value  

[23412 rows x 22 columns]

In [142]:
df = df[(df.Type == 'Nuclear Explosion') | (df.Type == 'Explosion')][df.Magnitude>6].copy()

C:\Users\skesh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


#### Slicing a dataframe

In [149]:
df.iloc[:4,5:8]

Depth Error  Depth Seismic Stations  Magnitude
2797          NaN                     NaN        6.3
2859          NaN                     NaN        6.8
2897          NaN                     NaN        6.9
3218          NaN                     NaN        6.4

In [162]:
df.iloc[:,2:8]

Longitude               Type  Depth  Depth Error  \
2797      78.853  Volcanic Eruption    0.0          NaN   
2859      55.161            Tsunami    0.0          NaN   
2897      54.177            Tsunami    0.0          NaN   
3218      55.094            Tsunami    0.0          NaN   
3286      54.063            Tsunami    0.0          NaN   
3593      54.641          Explosion    0.0          NaN   
3661      53.690            Tsunami    0.0          NaN   
3663      55.078            Tsunami    0.0          NaN   
5198      78.915            Tsunami    0.0          NaN   
5234      78.959            Tsunami    0.0          NaN   
5248      79.010            Tsunami    0.0          NaN   
5388      78.827            Tsunami    0.0          NaN   
5635      78.889            Tsunami    0.0          NaN   
6061      78.873            Tsunami    0.0          NaN   
6177      78.931            Tsunami    0.0          NaN   
6230      78.856            Tsunami    0.0          NaN   
6363      78.869            Tsunami    0.0          NaN   
6613      78.981            Tsunami    0.0          NaN   
6774      78.907            Tsunami    0.0          NaN   
7109      78.963            Tsunami    0.0          NaN   
7244      78.834            Tsunami    0.0          NaN   
7322      78.862            Tsunami    0.0          NaN   
8457      78.829            Tsunami    0.0          NaN   
8531      88.737            Tsunami    0.0          NaN   
8561      78.735            Tsunami    0.0          NaN   
8795      78.844            Tsunami    0.0          NaN   
8808      78.758            Tsunami    0.0          NaN   
8877      78.910            Tsunami    0.0          NaN   
8952      78.945            Tsunami    0.0          NaN   
8989      78.769            Tsunami    0.0          NaN   
9166      78.808            Tsunami    0.0          NaN   
9327      78.831            Tsunami    0.0          NaN   
10126     88.770            Tsunami    0.0          NaN   
10907     88.813            Tsunami    0.0          NaN   
12450     88.820            Tsunami    0.0          NaN   

       Depth Seismic Stations  Magnitude  
2797                      NaN        6.3  
2859                      NaN        6.8  
2897                      NaN        6.9  
3218                      NaN        6.4  
3286                      NaN        6.7  
3593                      NaN        6.4  
3661                      NaN        6.7  
3663                      NaN        6.5  
5198                      NaN        6.3  
5234                      NaN        6.1  
5248                      NaN        6.1  
5388                      NaN        6.1  
5635                      NaN        6.2  
6061                      NaN        6.2  
6177                      NaN        6.1  
6230                      NaN        6.1  
6363                      NaN        6.1  
6613                      NaN        6.1  
6774                      NaN        6.1  
7109                      NaN        6.2  
7244                      NaN        6.2  
7322                      NaN        6.1  
8457                      NaN        6.2  
8531                      NaN        6.2  
8561                      NaN        6.1  
8795                      NaN        6.1  
8808                      NaN        6.1  
8877                      NaN        6.1  
8952                      NaN        6.1  
8989                      NaN        6.1  
9166                      NaN        6.1  
9327                      NaN        6.1  
10126                     NaN        6.2  
10907                     NaN        6.5  
12450                     NaN        6.1

In [153]:
df.head(3)

Time  Latitude  Longitude               Type  Depth  Depth Error  \
2797  01:22:58    49.986     78.853  Nuclear Explosion    0.0          NaN   
2859  06:59:54    73.302     55.161  Nuclear Explosion    0.0          NaN   
2897  06:59:57    70.779     54.177  Nuclear Explosion    0.0          NaN   

      Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  ...  \
2797                     NaN        6.3             MB              NaN  ...   
2859                     NaN        6.8             MB              NaN  ...   
2897                     NaN        6.9             MB              NaN  ...   

      Horizontal Error  Root Mean Square          ID  Source  Location Source  \
2797               NaN               NaN  USP00002TP      US               US   
2859               NaN               NaN  USP00003DP      US               US   
2897               NaN               NaN  USP00003YA      US               US   

     Magnitude Source    Status New Magnitude new col Is_Disaster  
2797               US  Reviewed           6.8   value          No  
2859               US  Reviewed           7.3   value          No  
2897               US  Reviewed           7.4   value          No  

[3 rows x 23 columns]

#### Using loc to go to a cell and change a value

In [152]:
df.loc[2797]

Time                                   01:22:58
Latitude                                 49.986
Longitude                                78.853
Type                          Nuclear Explosion
Depth                                         0
Depth Error                                 NaN
Depth Seismic Stations                      NaN
Magnitude                                   6.3
Magnitude Type                               MB
Magnitude Error                             NaN
Magnitude Seismic Stations                  NaN
Azimuthal Gap                               NaN
Horizontal Distance                         NaN
Horizontal Error                            NaN
Root Mean Square                            NaN
ID                                   USP00002TP
Source                                       US
Location Source                              US
Magnitude Source                             US
Status                                 Reviewed
New Magnitude                           

In [154]:
df.loc[[2797]]

Time  Latitude  Longitude               Type  Depth  Depth Error  \
2797  01:22:58    49.986     78.853  Nuclear Explosion    0.0          NaN   

      Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  ...  \
2797                     NaN        6.3             MB              NaN  ...   

      Horizontal Error  Root Mean Square          ID  Source  Location Source  \
2797               NaN               NaN  USP00002TP      US               US   

     Magnitude Source    Status New Magnitude new col Is_Disaster  
2797               US  Reviewed           6.8   value          No  

[1 rows x 23 columns]

In [155]:
df.loc[2797,"Type"]

'Nuclear Explosion'

In [156]:
df.loc[2797,"Type"] = "Volcanic Eruption"

In [157]:
df.head(5)

Time  Latitude  Longitude               Type  Depth  Depth Error  \
2797  01:22:58    49.986     78.853  Volcanic Eruption    0.0          NaN   
2859  06:59:54    73.302     55.161  Nuclear Explosion    0.0          NaN   
2897  06:59:57    70.779     54.177  Nuclear Explosion    0.0          NaN   
3218  09:59:55    73.366     55.094  Nuclear Explosion    0.0          NaN   
3286  04:59:57    70.817     54.063  Nuclear Explosion    0.0          NaN   

      Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  ...  \
2797                     NaN        6.3             MB              NaN  ...   
2859                     NaN        6.8             MB              NaN  ...   
2897                     NaN        6.9             MB              NaN  ...   
3218                     NaN        6.4             MB              NaN  ...   
3286                     NaN        6.7             MB              NaN  ...   

      Horizontal Error  Root Mean Square          ID  Source  Location Source  \
2797               NaN               NaN  USP00002TP      US               US   
2859               NaN               NaN  USP00003DP      US               US   
2897               NaN               NaN  USP00003YA      US               US   
3218               NaN               NaN  USP00007UG      US               US   
3286               NaN               NaN  USP00008N6      US               US   

     Magnitude Source    Status New Magnitude new col Is_Disaster  
2797               US  Reviewed           6.8   value          No  
2859               US  Reviewed           7.3   value          No  
2897               US  Reviewed           7.4   value          No  
3218               US  Reviewed           6.9   value          No  
3286               US  Reviewed           7.2   value          No  

[5 rows x 23 columns]

#### Substituing of replacing a value using replace function

In [ ]:
df["Type"].replace("Nuclear Explosion","Tsunami",inplace=True)

In [160]:
df.Type.replace("Nuclear Explosion","Tsunami",inplace=True)

In [161]:
df.head()

Time  Latitude  Longitude               Type  Depth  Depth Error  \
2797  01:22:58    49.986     78.853  Volcanic Eruption    0.0          NaN   
2859  06:59:54    73.302     55.161            Tsunami    0.0          NaN   
2897  06:59:57    70.779     54.177            Tsunami    0.0          NaN   
3218  09:59:55    73.366     55.094            Tsunami    0.0          NaN   
3286  04:59:57    70.817     54.063            Tsunami    0.0          NaN   

      Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  ...  \
2797                     NaN        6.3             MB              NaN  ...   
2859                     NaN        6.8             MB              NaN  ...   
2897                     NaN        6.9             MB              NaN  ...   
3218                     NaN        6.4             MB              NaN  ...   
3286                     NaN        6.7             MB              NaN  ...   

      Horizontal Error  Root Mean Square          ID  Source  Location Source  \
2797               NaN               NaN  USP00002TP      US               US   
2859               NaN               NaN  USP00003DP      US               US   
2897               NaN               NaN  USP00003YA      US               US   
3218               NaN               NaN  USP00007UG      US               US   
3286               NaN               NaN  USP00008N6      US               US   

     Magnitude Source    Status New Magnitude new col Is_Disaster  
2797               US  Reviewed           6.8   value          No  
2859               US  Reviewed           7.3   value          No  
2897               US  Reviewed           7.4   value          No  
3218               US  Reviewed           6.9   value          No  
3286               US  Reviewed           7.2   value          No  

[5 rows x 23 columns]

In [166]:
d1 = {'Name' : ["A","B","C","D"],
     "ID":[1,2,3,4]}

df1 = pd.DataFrame(d1)
df1

Name  ID
0    A   1
1    B   2
2    C   3
3    D   4

In [167]:
d2 = {'Location' : ["North","South","Central"],
     "ID":[1,2,3]}

df2 = pd.DataFrame(d2)
df2

Location  ID
0    North   1
1    South   2
2  Central   3

In [168]:
pd.merge(df1,df2,how="inner",on="ID")

Name  ID Location
0    A   1    North
1    B   2    South
2    C   3  Central

In [170]:
pd.merge(df1,df2,how="left",on="ID")

Name  ID Location
0    A   1    North
1    B   2    South
2    C   3  Central
3    D   4      NaN

In [171]:
d1 = {'Name' : ["A","B","C","D"],
     "ID":[1,2,3,4]}

df1 = pd.DataFrame(d1)
df1

Name  ID
0    A   1
1    B   2
2    C   3
3    D   4

In [172]:
d1 = {'Name' : ["E","F"],
     "ID":[5,6]}

df3 = pd.DataFrame(d1)
df3

Name  ID
0    E   5
1    F   6

In [175]:
pd.concat([df1,df3]).reset_index(drop=True)

Name  ID
0    A   1
1    B   2
2    C   3
3    D   4
4    E   5
5    F   6

In [176]:
import pandas as pd

In [178]:
police = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pycon-2018-tutorial/master/police.csv')
police

stop_date stop_time  county_name driver_gender  driver_age_raw  \
0      2005-01-02     01:55          NaN             M          1985.0   
1      2005-01-18     08:15          NaN             M          1965.0   
2      2005-01-23     23:15          NaN             M          1972.0   
3      2005-02-20     17:15          NaN             M          1986.0   
4      2005-03-14     10:00          NaN             F          1984.0   
...           ...       ...          ...           ...             ...   
91736  2015-12-31     20:27          NaN             M          1986.0   
91737  2015-12-31     20:35          NaN             F          1982.0   
91738  2015-12-31     20:45          NaN             M          1992.0   
91739  2015-12-31     21:42          NaN             M          1993.0   
91740  2015-12-31     22:46          NaN             M          1959.0   

       driver_age driver_race                   violation_raw  \
0            20.0       White                        Speeding   
1            40.0       White                        Speeding   
2            33.0       White                        Speeding   
3            19.0       White                Call for Service   
4            21.0       White                        Speeding   
...           ...         ...                             ...   
91736        29.0       White                        Speeding   
91737        33.0       White  Equipment/Inspection Violation   
91738        23.0       White         Other Traffic Violation   
91739        22.0       White                        Speeding   
91740        56.0    Hispanic                        Speeding   

              violation  search_conducted search_type   stop_outcome  \
0              Speeding             False         NaN       Citation   
1              Speeding             False         NaN       Citation   
2              Speeding             False         NaN       Citation   
3                 Other             False         NaN  Arrest Driver   
4              Speeding             False         NaN       Citation   
...                 ...               ...         ...            ...   
91736          Speeding             False         NaN        Warning   
91737         Equipment             False         NaN        Warning   
91738  Moving violation             False         NaN        Warning   
91739          Speeding             False         NaN       Citation   
91740          Speeding             False         NaN       Citation   

      is_arrested stop_duration  drugs_related_stop  
0           False      0-15 Min               False  
1           False      0-15 Min               False  
2           False      0-15 Min               False  
3            True     16-30 Min               False  
4           False      0-15 Min               False  
...           ...           ...                 ...  
91736       False      0-15 Min               False  
91737       False      0-15 Min               False  
91738       False      0-15 Min               False  
91739       False      0-15 Min               False  
91740       False      0-15 Min               False  

[91741 rows x 15 columns]

# 1. Remove the column that only contains missing values

# 2. Who overspeeds more men or women?


# 3. Does gender affect who gets searched during a stop?



# 4. Which year had the least number of stops?


# 5. How does drug activity change by time of day?

# 1.

In [180]:
police.shape

(91741, 15)

In [179]:
police.isnull().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age_raw         5327
driver_age             5621
driver_race            5333
violation_raw          5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [181]:
police.drop(columns = "county_name",inplace=True)

In [182]:
police.shape

(91741, 14)

# 2.

In [184]:
police[police['violation']=="Speeding"]

stop_date stop_time driver_gender  driver_age_raw  driver_age  \
0      2005-01-02     01:55             M          1985.0        20.0   
1      2005-01-18     08:15             M          1965.0        40.0   
2      2005-01-23     23:15             M          1972.0        33.0   
4      2005-03-14     10:00             F          1984.0        21.0   
6      2005-04-01     17:30             M          1969.0        36.0   
...           ...       ...           ...             ...         ...   
91734  2015-12-31     20:20             M          1993.0        22.0   
91735  2015-12-31     20:25             M          1992.0        23.0   
91736  2015-12-31     20:27             M          1986.0        29.0   
91739  2015-12-31     21:42             M          1993.0        22.0   
91740  2015-12-31     22:46             M          1959.0        56.0   

      driver_race violation_raw violation  search_conducted search_type  \
0           White      Speeding  Speeding             False         NaN   
1           White      Speeding  Speeding             False         NaN   
2           White      Speeding  Speeding             False         NaN   
4           White      Speeding  Speeding             False         NaN   
6           White      Speeding  Speeding             False         NaN   
...           ...           ...       ...               ...         ...   
91734       White      Speeding  Speeding             False         NaN   
91735    Hispanic      Speeding  Speeding             False         NaN   
91736       White      Speeding  Speeding             False         NaN   
91739       White      Speeding  Speeding             False         NaN   
91740    Hispanic      Speeding  Speeding             False         NaN   

      stop_outcome is_arrested stop_duration  drugs_related_stop  
0         Citation       False      0-15 Min               False  
1         Citation       False      0-15 Min               False  
2         Citation       False      0-15 Min               False  
4         Citation       False      0-15 Min               False  
6         Citation       False      0-15 Min               False  
...            ...         ...           ...                 ...  
91734     Citation       False      0-15 Min               False  
91735     Citation       False      0-15 Min               False  
91736      Warning       False      0-15 Min               False  
91739     Citation       False      0-15 Min               False  
91740     Citation       False      0-15 Min               False  

[48463 rows x 14 columns]

In [185]:
police[police['violation']=="Speeding"]['driver_gender'].value_counts()

M    32979
F    15482
Name: driver_gender, dtype: int64

#### when a man is stopped how often is it for overspeeding

In [186]:
police[police["driver_gender"]=="M"]

stop_date stop_time driver_gender  driver_age_raw  driver_age  \
0      2005-01-02     01:55             M          1985.0        20.0   
1      2005-01-18     08:15             M          1965.0        40.0   
2      2005-01-23     23:15             M          1972.0        33.0   
3      2005-02-20     17:15             M          1986.0        19.0   
5      2005-03-23     09:45             M          1982.0        23.0   
...           ...       ...           ...             ...         ...   
91735  2015-12-31     20:25             M          1992.0        23.0   
91736  2015-12-31     20:27             M          1986.0        29.0   
91738  2015-12-31     20:45             M          1992.0        23.0   
91739  2015-12-31     21:42             M          1993.0        22.0   
91740  2015-12-31     22:46             M          1959.0        56.0   

      driver_race                   violation_raw         violation  \
0           White                        Speeding          Speeding   
1           White                        Speeding          Speeding   
2           White                        Speeding          Speeding   
3           White                Call for Service             Other   
5           Black  Equipment/Inspection Violation         Equipment   
...           ...                             ...               ...   
91735    Hispanic                        Speeding          Speeding   
91736       White                        Speeding          Speeding   
91738       White         Other Traffic Violation  Moving violation   
91739       White                        Speeding          Speeding   
91740    Hispanic                        Speeding          Speeding   

       search_conducted search_type   stop_outcome is_arrested stop_duration  \
0                 False         NaN       Citation       False      0-15 Min   
1                 False         NaN       Citation       False      0-15 Min   
2                 False         NaN       Citation       False      0-15 Min   
3                 False         NaN  Arrest Driver        True     16-30 Min   
5                 False         NaN       Citation       False      0-15 Min   
...                 ...         ...            ...         ...           ...   
91735             False         NaN       Citation       False      0-15 Min   
91736             False         NaN        Warning       False      0-15 Min   
91738             False         NaN        Warning       False      0-15 Min   
91739             False         NaN       Citation       False      0-15 Min   
91740             False         NaN       Citation       False      0-15 Min   

       drugs_related_stop  
0                   False  
1                   False  
2                   False  
3                   False  
5                   False  
...                   ...  
91735               False  
91736               False  
91738               False  
91739               False  
91740               False  

[62895 rows x 14 columns]

In [187]:
police[police["driver_gender"]=="M"]["violation"].value_counts()

Speeding               32979
Moving violation       13020
Equipment               8533
Other                   3627
Registration/plates     2419
Seat belt               2317
Name: violation, dtype: int64

In [188]:
police[police["driver_gender"]=="M"]["violation"].value_counts(normalize=True)

Speeding               0.524350
Moving violation       0.207012
Equipment              0.135671
Other                  0.057668
Registration/plates    0.038461
Seat belt              0.036839
Name: violation, dtype: float64

#### when a woman is stopped how often is it for overspeeding

In [190]:
police[police["driver_gender"]=="F"]["violation"].value_counts()

Speeding               15482
Moving violation        3204
Equipment               2487
Registration/plates     1013
Other                    690
Seat belt                635
Name: violation, dtype: int64

In [189]:
police[police["driver_gender"]=="F"]["violation"].value_counts(normalize=True)

Speeding               0.658500
Moving violation       0.136277
Equipment              0.105780
Registration/plates    0.043086
Other                  0.029348
Seat belt              0.027009
Name: violation, dtype: float64

#### combining both the outputs in to single line

In [191]:
police.groupby("driver_gender")["violation"].value_counts(normalize=True)

driver_gender  violation          
F              Speeding               0.658500
               Moving violation       0.136277
               Equipment              0.105780
               Registration/plates    0.043086
               Other                  0.029348
               Seat belt              0.027009
M              Speeding               0.524350
               Moving violation       0.207012
               Equipment              0.135671
               Other                  0.057668
               Registration/plates    0.038461
               Seat belt              0.036839
Name: violation, dtype: float64

# 3.

In [195]:
police["search_conducted"].value_counts()

False    88545
True      3196
Name: search_conducted, dtype: int64

In [196]:
police.groupby("driver_gender")["search_conducted"].mean()

driver_gender
F    0.020033
M    0.043326
Name: search_conducted, dtype: float64

In [198]:
police.groupby(["driver_gender","driver_race"])["search_conducted"].mean()

driver_gender  driver_race
F              Asian          0.011696
               Black          0.041473
               Hispanic       0.036879
               Other          0.000000
               White          0.015604
M              Asian          0.025773
               Black          0.070675
               Hispanic       0.067444
               Other          0.014019
               White          0.033895
Name: search_conducted, dtype: float64

# 4.

In [200]:
police["stop_date"]

0        2005-01-02
1        2005-01-18
2        2005-01-23
3        2005-02-20
4        2005-03-14
            ...    
91736    2015-12-31
91737    2015-12-31
91738    2015-12-31
91739    2015-12-31
91740    2015-12-31
Name: stop_date, Length: 91741, dtype: object

In [201]:
police["stop_date"].str.slice(0,4)

0        2005
1        2005
2        2005
3        2005
4        2005
         ... 
91736    2015
91737    2015
91738    2015
91739    2015
91740    2015
Name: stop_date, Length: 91741, dtype: object

In [202]:
police["Year"] = police["stop_date"].str.slice(0,4)

In [203]:
police

stop_date stop_time driver_gender  driver_age_raw  driver_age  \
0      2005-01-02     01:55             M          1985.0        20.0   
1      2005-01-18     08:15             M          1965.0        40.0   
2      2005-01-23     23:15             M          1972.0        33.0   
3      2005-02-20     17:15             M          1986.0        19.0   
4      2005-03-14     10:00             F          1984.0        21.0   
...           ...       ...           ...             ...         ...   
91736  2015-12-31     20:27             M          1986.0        29.0   
91737  2015-12-31     20:35             F          1982.0        33.0   
91738  2015-12-31     20:45             M          1992.0        23.0   
91739  2015-12-31     21:42             M          1993.0        22.0   
91740  2015-12-31     22:46             M          1959.0        56.0   

      driver_race                   violation_raw         violation  \
0           White                        Speeding          Speeding   
1           White                        Speeding          Speeding   
2           White                        Speeding          Speeding   
3           White                Call for Service             Other   
4           White                        Speeding          Speeding   
...           ...                             ...               ...   
91736       White                        Speeding          Speeding   
91737       White  Equipment/Inspection Violation         Equipment   
91738       White         Other Traffic Violation  Moving violation   
91739       White                        Speeding          Speeding   
91740    Hispanic                        Speeding          Speeding   

       search_conducted search_type   stop_outcome is_arrested stop_duration  \
0                 False         NaN       Citation       False      0-15 Min   
1                 False         NaN       Citation       False      0-15 Min   
2                 False         NaN       Citation       False      0-15 Min   
3                 False         NaN  Arrest Driver        True     16-30 Min   
4                 False         NaN       Citation       False      0-15 Min   
...                 ...         ...            ...         ...           ...   
91736             False         NaN        Warning       False      0-15 Min   
91737             False         NaN        Warning       False      0-15 Min   
91738             False         NaN        Warning       False      0-15 Min   
91739             False         NaN       Citation       False      0-15 Min   
91740             False         NaN       Citation       False      0-15 Min   

       drugs_related_stop  Year  
0                   False  2005  
1                   False  2005  
2                   False  2005  
3                   False  2005  
4                   False  2005  
...                   ...   ...  
91736               False  2015  
91737               False  2015  
91738               False  2015  
91739               False  2015  
91740               False  2015  

[91741 rows x 15 columns]

In [204]:
police["Year"].value_counts()

2012    10970
2006    10639
2007     9476
2014     9228
2008     8752
2015     8599
2011     8126
2013     7924
2009     7908
2010     7561
2005     2558
Name: Year, dtype: int64

In [205]:
police["Year"].value_counts().index

Index(['2012', '2006', '2007', '2014', '2008', '2015', '2011', '2013', '2009',
       '2010', '2005'],
      dtype='object')

In [208]:
most_stopage_year = police["Year"].value_counts().index[0]
least_stopage_year = police["Year"].value_counts().index[-1]

In [209]:
most_stopage_year

'2012'

In [210]:
least_stopage_year

'2005'

In [212]:
police

stop_date stop_time driver_gender  driver_age_raw  driver_age  \
0      2005-01-02     01:55             M          1985.0        20.0   
1      2005-01-18     08:15             M          1965.0        40.0   
2      2005-01-23     23:15             M          1972.0        33.0   
3      2005-02-20     17:15             M          1986.0        19.0   
4      2005-03-14     10:00             F          1984.0        21.0   
...           ...       ...           ...             ...         ...   
91736  2015-12-31     20:27             M          1986.0        29.0   
91737  2015-12-31     20:35             F          1982.0        33.0   
91738  2015-12-31     20:45             M          1992.0        23.0   
91739  2015-12-31     21:42             M          1993.0        22.0   
91740  2015-12-31     22:46             M          1959.0        56.0   

      driver_race                   violation_raw         violation  \
0           White                        Speeding          Speeding   
1           White                        Speeding          Speeding   
2           White                        Speeding          Speeding   
3           White                Call for Service             Other   
4           White                        Speeding          Speeding   
...           ...                             ...               ...   
91736       White                        Speeding          Speeding   
91737       White  Equipment/Inspection Violation         Equipment   
91738       White         Other Traffic Violation  Moving violation   
91739       White                        Speeding          Speeding   
91740    Hispanic                        Speeding          Speeding   

       search_conducted search_type   stop_outcome is_arrested stop_duration  \
0                 False         NaN       Citation       False      0-15 Min   
1                 False         NaN       Citation       False      0-15 Min   
2                 False         NaN       Citation       False      0-15 Min   
3                 False         NaN  Arrest Driver        True     16-30 Min   
4                 False         NaN       Citation       False      0-15 Min   
...                 ...         ...            ...         ...           ...   
91736             False         NaN        Warning       False      0-15 Min   
91737             False         NaN        Warning       False      0-15 Min   
91738             False         NaN        Warning       False      0-15 Min   
91739             False         NaN       Citation       False      0-15 Min   
91740             False         NaN       Citation       False      0-15 Min   

       drugs_related_stop  Year  
0                   False  2005  
1                   False  2005  
2                   False  2005  
3                   False  2005  
4                   False  2005  
...                   ...   ...  
91736               False  2015  
91737               False  2015  
91738               False  2015  
91739               False  2015  
91740               False  2015  

[91741 rows x 15 columns]

In [216]:

police["stop_date"].str.cat(police["stop_time"],sep=' ')

0        2005-01-02 01:55
1        2005-01-18 08:15
2        2005-01-23 23:15
3        2005-02-20 17:15
4        2005-03-14 10:00
               ...       
91736    2015-12-31 20:27
91737    2015-12-31 20:35
91738    2015-12-31 20:45
91739    2015-12-31 21:42
91740    2015-12-31 22:46
Name: stop_date, Length: 91741, dtype: object

In [217]:
combined = police["stop_date"].str.cat(police["stop_time"],sep=' ')

In [218]:
police['stop_datetime'] = pd.to_datetime(combined)

In [220]:
police.dtypes

stop_date                     object
stop_time                     object
driver_gender                 object
driver_age_raw               float64
driver_age                   float64
driver_race                   object
violation_raw                 object
violation                     object
search_conducted                bool
search_type                   object
stop_outcome                  object
is_arrested                   object
stop_duration                 object
drugs_related_stop              bool
Year                          object
stop_datetime         datetime64[ns]
dtype: object

In [230]:
police['stop_datetime'].dt.year.value_counts()

2012    10970
2006    10639
2007     9476
2014     9228
2008     8752
2015     8599
2011     8126
2013     7924
2009     7908
2010     7561
2005     2558
Name: stop_datetime, dtype: int64

In [231]:
most_stopage_year = police['stop_datetime'].dt.year.value_counts().index[0]
least_stopage_year = police['stop_datetime'].dt.year.value_counts().index[-1]

# 5.

In [237]:
police["Time"] = police['stop_datetime'].dt.hour

In [238]:
police.groupby("Time").drugs_related_stop.mean()

Time
0     0.019728
1     0.013507
2     0.015462
3     0.017065
4     0.011811
5     0.004762
6     0.003040
7     0.003281
8     0.002687
9     0.006288
10    0.005714
11    0.006976
12    0.004467
13    0.010326
14    0.007810
15    0.006416
16    0.005723
17    0.005517
18    0.010148
19    0.011596
20    0.008084
21    0.013342
22    0.013533
23    0.016344
Name: drugs_related_stop, dtype: float64

In [239]:
police.groupby("Time").drugs_related_stop.mean().plot()